// Lab 8 (anchor scope). Columns: key, en, es, ar, he, ru, fr.
export const rows=[
 ['title','Anchor scope: why a long rode holds','Relación de fondeo: por qué una línea larga agarra','نسبة حبل المرساة: لماذا يثبت الحبل الطويل','יחס העגינה: למה חבל ארוך מחזיק','Кратность якорного каната: почему длинный канат держит','Rapport de mouillage : pourquoi une longue ligne tient'],
 ['caption','Side view of a yacht lying back on its anchor, rode pulled tight by the wind. Scope is the rode length divided by the depth plus the bow roller height. More scope makes the pull at the anchor flatter, so it digs in; the inset shows the swing circle from above.','Vista lateral de un velero fondeado, con la línea tensa por el viento. La relación es la longitud de la línea dividida entre la profundidad más la altura del rodillo de proa. Más relación hace el tirón en el ancla más horizontal y así se clava; el recuadro muestra el círculo de borneo desde arriba.','منظر جانبي ليخت راسٍ على مرساته، والحبل مشدود بفعل الرياح. النسبة هي طول الحبل مقسومًا على العمق مضافًا إليه ارتفاع بكرة المقدمة. كلما زادت النسبة صار السحب على المرساة أفقيًا أكثر فتنغرس؛ ويُظهر الإطار دائرة الدوران من الأعلى.','מבט מהצד על יאכטה שעוגנת, החבל מתוח בגלל הרוח. היחס הוא אורך החבל חלקי העומק ועוד גובה גלגלת החרטום. יחס גדול יותר הופך את המשיכה בעוגן לשטוחה יותר, ולכן הוא ננעץ; המסגרת מציגה את מעגל הסחרור מלמעלה.','Вид сбоку на яхту на якоре, канат натянут ветром. Кратность — длина каната, делённая на глубину плюс высоту носового роульса. Чем больше кратность, тем положе тяга у якоря, и он зарывается; на врезке — круг разворота сверху.','Vue de côté d’un voilier au mouillage, ligne tendue par le vent. Le rapport est la longueur de ligne divisée par la profondeur plus la hauteur du davier. Plus de rapport rend la traction sur l’ancre plus horizontale, elle croche ; l’encart montre le cercle d’évitage vu de dessus.'],
 ['depthControl','Water depth','Profundidad','عمق الماء','עומק המים','Глубина','Profondeur'],
 ['rodeControl','Rode let out','Línea largada','طول الحبل المُرخى','אורך החבל ששוחרר','Вытравлено каната','Longueur de ligne filée'],
 ['scopeLine','Scope {scope}:1 = {rode} m ÷ {vertical} m','Relación {scope}:1 = {rode} m ÷ {vertical} m','النسبة {scope}:1 = {rode} م ÷ {vertical} م','יחס {scope}:1 = {rode} מ׳ ÷ {vertical} מ׳','Кратность {scope}:1 = {rode} м ÷ {vertical} м','Rapport {scope}:1 = {rode} m ÷ {vertical} m'],
 ['above','Seen from above','Visto desde arriba','منظر من الأعلى','מבט מלמעלה','Вид сверху','Vu de dessus'],
 ['swing','Swing circle {diameter} m across','Círculo de borneo de {diameter} m','دائرة دوران قطرها {diameter} م','מעגל סחרור בקוטר {diameter} מ׳','Круг разворота {diameter} м','Cercle d’évitage de {diameter} m'],
 ['flat','Pull is flat ({angle}° at the anchor, scope {scope}:1): the anchor digs in and holds.','Tirón horizontal ({angle}° en el ancla, relación {scope}:1): el ancla se clava y agarra.','السحب أفقي ({angle}° عند المرساة، النسبة {scope}:1): تنغرس المرساة وتثبت.','המשיכה שטוחה ({angle}° בעוגן, יחס {scope}:1): העוגן ננעץ ומחזיק.','Тяга пологая ({angle}° у якоря, кратность {scope}:1): якорь зарывается и держит.','Traction horizontale ({angle}° à l’ancre, rapport {scope}:1) : l’ancre croche et tient.'],
 ['steep','Pull is steep ({angle}° at the anchor, scope {scope}:1): the anchor may break out and drag. Let out at least {need} m.','Tirón empinado ({angle}° en el ancla, relación {scope}:1): el ancla puede soltarse y garrear. Larga al menos {need} m.','السحب حاد ({angle}° عند المرساة، النسبة {scope}:1): قد تنقلع المرساة وتنجرف. أرخِ {need} م على الأقل.','המשיכה תלולה ({angle}° בעוגן, יחס {scope}:1): העוגן עלול להיעקר ולהיגרר. שחררו לפחות {need} מ׳.','Тяга крутая ({angle}° у якоря, кратность {scope}:1): якорь может сорваться и ползти. Вытравите не меньше {need} м.','Traction trop raide ({angle}° à l’ancre, rapport {scope}:1) : l’ancre peut décrocher et chasser. Filez au moins {need} m.'],
 ['upDown','The rode ({rode} m) is shorter than the depth plus the bow height: the pull is straight up, so the anchor lifts off the bottom.','La línea ({rode} m) es más corta que la profundidad más la altura de proa: el tirón es vertical y el ancla se levanta del fondo.','الحبل ({rode} م) أقصر من العمق مع ارتفاع المقدمة: السحب عمودي، فترتفع المرساة عن القاع.','החבל ({rode} מ׳) קצר מהעומק ועוד גובה החרטום: המשיכה ישר למעלה, ולכן העוגן מתרומם מהקרקעית.','Канат ({rode} м) короче глубины плюс высоты носа: тяга вертикальна, и якорь отрывается от дна.','La ligne ({rode} m) est plus courte que la profondeur plus la hauteur d’étrave : la traction est verticale, l’ancre quitte le fond.'],
 ['taskShortest','At 5 m depth, find the shortest rode that keeps the pull flat.','A 5 m de profundidad, busca la línea más corta que mantenga el tirón horizontal.','عند عمق 5 م، اعثر على أقصر حبل يبقي السحب أفقيًا.','בעומק 5 מ׳, מצאו את החבל הקצר ביותר שמשאיר את המשיכה שטוחה.','На глубине 5 м найдите самый короткий канат, при котором тяга остаётся пологой.','À 5 m de fond, trouvez la ligne la plus courte qui garde la traction horizontale.'],
 ['taskDeeper','Double the depth, then let out enough rode to keep the pull flat.','Duplica la profundidad y larga línea suficiente para mantener el tirón horizontal.','ضاعف العمق، ثم أرخِ ما يكفي من الحبل ليبقى السحب أفقيًا.','הכפילו את העומק, ואז שחררו מספיק חבל כדי שהמשיכה תישאר שטוחה.','Удвойте глубину и вытравите достаточно каната, чтобы тяга осталась пологой.','Doublez la profondeur, puis filez assez de ligne pour garder la traction horizontale.'],
 ['taskSwing','Let out more rode and watch the swing circle grow.','Larga más línea y mira cómo crece el círculo de borneo.','أرخِ مزيدًا من الحبل وراقب دائرة الدوران تكبر.','שחררו עוד חבל וראו את מעגל הסחרור גדל.','Вытравите больше каната и посмотрите, как растёт круг разворота.','Filez plus de ligne et regardez le cercle d’évitage grandir.'],
 ['taskBreakout','Shorten the rode until it is straight up and down and the anchor lifts out.','Acorta la línea hasta que quede a pique y el ancla salga.','قصّر الحبل حتى يصبح عموديًا وترتفع المرساة.','קצרו את החבל עד שהוא אנכי והעוגן מתרומם.','Выбирайте канат, пока он не встанет вертикально и якорь не оторвётся.','Raccourcissez la ligne jusqu’à ce qu’elle soit à pic et que l’ancre dérape.'],
];
