// Lab 6 (apparent wind). Columns: key, en, es, ar, he, ru, fr.
export const rows=[
 ['title','Apparent wind: true wind plus the boat’s own breeze','Viento aparente: viento real más la brisa del propio barco','الرياح الظاهرية: الرياح الحقيقية مع نسيم حركة القارب','רוח מדומה: הרוח האמיתית ועוד הבריזה של הסירה עצמה','Вымпельный ветер: истинный ветер плюс встречный поток от хода','Vent apparent : vent réel plus la brise due au bateau'],
 ['caption','Top view, bow up, true wind from the right. The boat’s motion makes its own breeze from ahead (grey). Added to the true wind (blue), it gives the apparent wind (gold): the wind the sails feel.','Vista desde arriba, proa hacia arriba, viento real desde la derecha. El movimiento del barco crea su propia brisa desde proa (gris). Sumada al viento real (azul), da el viento aparente (dorado): el que sienten las velas.','منظر علوي، المقدمة إلى الأعلى، والرياح الحقيقية من اليمين. تصنع حركة القارب نسيمًا من الأمام (رمادي). عند جمعه مع الرياح الحقيقية (أزرق) نحصل على الرياح الظاهرية (ذهبي): وهي ما تشعر به الأشرعة.','מבט מלמעלה, החרטום למעלה, הרוח האמיתית מימין. תנועת הסירה יוצרת בריזה משלה מלפנים (אפור). יחד עם הרוח האמיתית (כחול) מתקבלת הרוח המדומה (זהב): הרוח שהמפרשים מרגישים.','Вид сверху, нос вверху, истинный ветер справа. Ход яхты создаёт встречный поток (серый). Вместе с истинным ветром (синий) он даёт вымпельный ветер (золотой) — его и чувствуют паруса.','Vue de dessus, étrave en haut, vent réel venant de la droite. Le mouvement du bateau crée sa propre brise venant de l’avant (gris). Ajoutée au vent réel (bleu), elle donne le vent apparent (doré) : celui que sentent les voiles.'],
 ['speedControl','Boat speed','Velocidad del barco','سرعة القارب','מהירות הסירה','Скорость яхты','Vitesse du bateau'],
 ['angleControl','True wind angle from the bow','Ángulo del viento real desde la proa','زاوية الرياح الحقيقية من المقدمة','זווית הרוח האמיתית מהחרטום','Угол истинного ветра от носа','Angle du vent réel depuis l’étrave'],
 ['trueLabel','True wind','Viento real','الرياح الحقيقية','רוח אמיתית','Истинный ветер','Vent réel'],
 ['motionLabel','Breeze from boat motion','Brisa por el movimiento','نسيم حركة القارب','בריזה מתנועת הסירה','Поток от хода','Brise due à la vitesse'],
 ['feltLabel','Apparent wind','Viento aparente','الرياح الظاهرية','רוח מדומה','Вымпельный ветер','Vent apparent'],
 ['still','Boat stopped: the sails feel the true wind, {speed} knots from {angle}°.','Barco parado: las velas sienten el viento real, {speed} nudos desde {angle}°.','القارب متوقف: تشعر الأشرعة بالرياح الحقيقية، {speed} عقدة من {angle}°.','הסירה עומדת: המפרשים מרגישים את הרוח האמיתית, {speed} קשר מ־{angle}°.','Яхта стоит: паруса чувствуют истинный ветер, {speed} уз с {angle}°.','Bateau arrêté : les voiles sentent le vent réel, {speed} nœuds du {angle}°.'],
 ['forwardStronger','Apparent wind: {speed} knots from {angle}°, {shift}° further forward and stronger than the true wind.','Viento aparente: {speed} nudos desde {angle}°, {shift}° más a proa y más fuerte que el viento real.','الرياح الظاهرية: {speed} عقدة من {angle}°، أبعد إلى الأمام بـ {shift}° وأقوى من الرياح الحقيقية.','רוח מדומה: {speed} קשר מ־{angle}°, {shift}° יותר קדימה וחזקה יותר מהרוח האמיתית.','Вымпельный ветер: {speed} уз с {angle}°, на {shift}° острее и сильнее истинного.','Vent apparent : {speed} nœuds du {angle}°, {shift}° plus en avant et plus fort que le vent réel.'],
 ['forwardWeaker','Apparent wind: {speed} knots from {angle}°, {shift}° further forward but weaker than the true wind.','Viento aparente: {speed} nudos desde {angle}°, {shift}° más a proa pero más flojo que el viento real.','الرياح الظاهرية: {speed} عقدة من {angle}°، أبعد إلى الأمام بـ {shift}° لكنها أضعف من الرياح الحقيقية.','רוח מדומה: {speed} קשר מ־{angle}°, {shift}° יותר קדימה אבל חלשה יותר מהרוח האמיתית.','Вымпельный ветер: {speed} уз с {angle}°, на {shift}° острее, но слабее истинного.','Vent apparent : {speed} nœuds du {angle}°, {shift}° plus en avant mais plus faible que le vent réel.'],
 ['headOn','Apparent wind: {speed} knots from dead ahead. Motion adds to the true wind.','Viento aparente: {speed} nudos de proa. El movimiento se suma al viento real.','الرياح الظاهرية: {speed} عقدة من الأمام مباشرة. تُضاف الحركة إلى الرياح الحقيقية.','רוח מדומה: {speed} קשר ישר מלפנים. התנועה מתווספת לרוח האמיתית.','Вымпельный ветер: {speed} уз прямо в нос. Ход складывается с истинным ветром.','Vent apparent : {speed} nœuds droit devant. La vitesse s’ajoute au vent réel.'],
 ['downwind','Apparent wind: {speed} knots from astern, weaker than the true {trueSpeed} knots: you move with the air.','Viento aparente: {speed} nudos de popa, más flojo que los {trueSpeed} nudos reales: te mueves con el aire.','الرياح الظاهرية: {speed} عقدة من الخلف، أضعف من {trueSpeed} عقدة حقيقية: أنت تتحرك مع الهواء.','רוח מדומה: {speed} קשר מאחור, חלשה מ־{trueSpeed} הקשר האמיתיים: אתם נעים עם האוויר.','Вымпельный ветер: {speed} уз с кормы, слабее истинных {trueSpeed} уз: вы движетесь вместе с воздухом.','Vent apparent : {speed} nœuds de l’arrière, plus faible que les {trueSpeed} nœuds réels : vous avancez avec l’air.'],
 ['same','Apparent wind: {speed} knots from {angle}°.','Viento aparente: {speed} nudos desde {angle}°.','الرياح الظاهرية: {speed} عقدة من {angle}°.','רוח מדומה: {speed} קשר מ־{angle}°.','Вымпельный ветер: {speed} уз с {angle}°.','Vent apparent : {speed} nœuds du {angle}°.'],
 ['taskSpeedUp','On a beam reach, speed up and watch the apparent wind move forward.','De través, acelera y mira cómo el viento aparente se mueve hacia proa.','عند الإبحار بعرض الريح، زد السرعة وراقب الرياح الظاهرية تتحرك إلى الأمام.','ברוח צד, האיצו וראו את הרוח המדומה זזה קדימה.','В галфвинд разгонитесь и посмотрите, как вымпельный ветер заходит вперёд.','Au travers, accélérez et regardez le vent apparent avancer.'],
 ['taskBearAway','Bear away to a broad reach and watch the apparent wind weaken.','Arriba a un largo y mira cómo se debilita el viento aparente.','ابتعد عن الريح إلى إبحار بريح خلفية جانبية وراقب الرياح الظاهرية تضعف.','התרחקו מהרוח לרוח גבית צדית וראו את הרוח המדומה נחלשת.','Уваливайтесь в бакштаг и посмотрите, как вымпельный ветер слабеет.','Abattez au grand largue et regardez le vent apparent faiblir.'],
 ['taskFaster','Sail faster than the true wind and see the apparent wind come from ahead of the beam.','Navega más rápido que el viento real y mira cómo el viento aparente llega por delante del través.','أبحر أسرع من الرياح الحقيقية وانظر كيف تأتي الرياح الظاهرية من أمام عرض القارب.','הפליגו מהר יותר מהרוח האמיתית וראו שהרוח המדומה מגיעה מלפני הרוחב.','Идите быстрее истинного ветра и увидите, что вымпельный ветер дует спереди траверза.','Allez plus vite que le vent réel et voyez le vent apparent venir de l’avant du travers.'],
];
