import { initializeAnchoredScenario } from '../src/anchor.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {lessons,modules} from '../src/learning/curriculum.js';
import {restoreProgress,recordFor,masteredIds,checkKnowledge,beginAttempt,advanceAttempt,recordEvent,crossingKind,invalidateAttempt} from '../src/learning/engine.js';
const state=()=>({heading:45,windDirection:315,windSpeed:12,speed:3,trim:34,mainSheet:34,suggestedMainSheet:34,sails:1,mainHoist:1,jibHoist:1,anchor:false,anchorScope:6,mainFlow:'Drawing',depth:28,x:0,z:0,throttle:0,grounded:false});
const run=(a,l,s,p,seconds)=>{for(let t=0;t<seconds;t+=.1)advanceAttempt(a,l,s,.1,p);};
test('curriculum is complete and all quiz answers/step kinds are valid',()=>{assert.equal(lessons.length,52);assert.equal(modules.length,13);const kinds=new Set(['camera','event','sails','speedAbove','heading','windAngle','trim','tack','gybe','recover','reef','coast','anchor','waypoint','engineWaypoint','engineStop']);for(const [i,l]of lessons.entries()){assert.equal(l.prerequisite,i?lessons[i-1].id:null);assert.equal(l.quiz.length,['sail-04','sail-05'].includes(l.id)?3:2);for(const q of l.quiz)assert.ok(q.options[q.correct]&&q.explanation);for(const step of l.practice?.steps??[])assert.ok(kinds.has(step.kind));}});
test('mastery needs correct knowledge and prior mastery; practical lessons also need evidence',()=>{const p=restoreProgress(null);const first=lessons[0],second=lessons[1],practical=lessons.find(l=>l.practice);checkKnowledge(p,second,second.quiz.map(q=>q.correct));assert.equal(masteredIds(p).size,0);const bad=checkKnowledge(p,first,first.quiz.map(q=>(q.correct+1)%q.options.length));assert.equal(bad.correct,false);assert.equal(masteredIds(p).size,0);checkKnowledge(p,first,first.quiz.map(q=>q.correct));if(first.decisionScenarioId||second.decisionScenarioId){assert.equal(masteredIds(p).size,0);if(first.decisionScenarioId)recordFor(p,first.id).decision=true;if(second.decisionScenarioId)recordFor(p,second.id).decision=true;}assert.equal(masteredIds(p).size,2);checkKnowledge(p,practical,practical.quiz.map(q=>q.correct));assert.ok(!masteredIds(p).has(practical.id));assert.equal(checkKnowledge(p,first,[]).complete,false);});
test('storage ignores old badges, malformed input, unknown IDs and untyped evidence',()=>{assert.equal(Object.keys(restoreProgress('[0,1,2]').records).length,0);assert.equal(Object.keys(restoreProgress('bad json').records).length,0);const p=restoreProgress({version:1,selected:'invalid',records:{'sail-01':{knowledge:'yes',practice:true,attempts:-1,hints:Infinity},'made-up':{knowledge:true}}});assert.equal(p.selected,'sail-01');assert.equal(p.records['sail-01'].knowledge,false);assert.equal(p.records['sail-01'].practice,false);assert.equal(p.records['sail-01'].hints,0);assert.ok(!p.records['made-up']);});
test('continuous holds reset outside tolerance and paused/large time jumps earn no credit',()=>{const l=lessons.find(l=>l.title==='Hold a steady course'),s=state(),p=restoreProgress(null),a=beginAttempt(l,s,p);run(a,l,s,p,5);assert.ok(a.held>=4.9);s.heading=70;run(a,l,s,p,1);assert.equal(a.held,0);s.heading=45;advanceAttempt(a,l,s,60,p);assert.equal(a.held,0);run(a,l,s,p,10.2);assert.equal(a.status,'passed');assert.equal(recordFor(p,l.id).practice,true);assert.ok(!masteredIds(p).has(l.id));});
test('ordered events cannot be banked for later checkpoints',()=>{const l=lessons.find(l=>l.title==='Read the instruments'),s=state(),p=restoreProgress(null),a=beginAttempt(l,s,p);recordEvent(a,'event','chart');run(a,l,s,p,1);assert.equal(a.index,0);recordEvent(a,'camera','deck');run(a,l,s,p,.2);assert.equal(a.index,1);run(a,l,s,p,1);assert.equal(a.status,'active');recordEvent(a,'event','chart');run(a,l,s,p,.2);assert.equal(a.status,'passed');});
test('bow crossing and stern crossing are distinct including a zero-angle frame',()=>{assert.equal(crossingKind(-2,2),'tack');assert.equal(crossingKind(-179,179),'gybe');assert.equal(crossingKind(-20,-10),null);const l=lessons.find(l=>l.practice?.steps[0].kind==='tack'),s=state(),p=restoreProgress(null);s.heading=265;const a=beginAttempt(l,s,p);s.heading=136;run(a,l,s,p,.1);s.heading=134;run(a,l,s,p,.1);s.heading=5;run(a,l,s,p,7);assert.equal(a.status,'active','gybe must not pass a tack');s.heading=314;run(a,l,s,p,.1);s.heading=315;run(a,l,s,p,.1);s.heading=316;run(a,l,s,p,.1);s.heading=5;run(a,l,s,p,6.2);assert.equal(a.status,'passed');});
test('grounding, engine, weather changes, resets and early anchoring invalidate evidence',()=>{const l=lessons.find(l=>l.title==='Hold a steady course');for(const patch of [{grounded:true},{throttle:.2},{windDirection:314},{currentSpeed:1},{anchor:true}]){const s=state(),p=restoreProgress(null),a=beginAttempt(l,s,p);Object.assign(s,patch);run(a,l,s,p,12);assert.equal(a.status,'invalid');assert.equal(recordFor(p,l.id).practice,false);}const s=state(),p=restoreProgress(null),a=beginAttempt(l,s,p);invalidateAttempt(a,p,'Boat reset');run(a,l,s,p,12);assert.equal(a.status,'invalid');});
test('anchor is accepted only after coasting with sails lowered and anchor up',()=>{const l=lessons.find(l=>l.title==='Stop, then anchor'),s=state(),p=restoreProgress(null),a=beginAttempt(l,s,p);s.speed=.1;s.mainHoist=s.jibHoist=s.sails=0;run(a,l,s,p,3.2);assert.equal(a.index,1);initializeAnchoredScenario(s,{rode:45});run(a,l,s,p,4.2);assert.equal(a.status,'passed');});

test('per-question feedback can retain mistake counts without double-counting a whole quiz',()=>{const p=restoreProgress(null),l=lessons[0],r=recordFor(p,l.id);r.wrongAnswers=1;const incomplete=checkKnowledge(p,l,[0,null],{countWrongAnswers:false});assert.equal(incomplete.complete,false);assert.equal(r.knowledge,false);assert.equal(r.wrongAnswers,1);checkKnowledge(p,l,[0,0],{countWrongAnswers:false});assert.equal(r.wrongAnswers,1);assert.equal(r.knowledge,false);checkKnowledge(p,l,l.quiz.map(q=>q.correct),{countWrongAnswers:false});assert.equal(r.knowledge,true);assert.equal(r.wrongAnswers,1);});
test('advanced decisions preserve the original progress chain and never award simulated practice',()=>{const p=restoreProgress(null);for(const l of lessons.filter(l=>l.module==='coastal-decisions')){assert.equal(l.practice,null);assert.equal(l.level,'advanced');checkKnowledge(p,l,l.quiz.map(q=>q.correct));assert.equal(recordFor(p,l.id).practice,false);}assert.equal(masteredIds(p).size,0);});
