import { APPARENT_WIND_LAB } from './apparent-wind.js';
// Authored positions use the same metres, compass bearings and depth model as the chart.
export const CHALLENGES = [
  {
    id: 'rescue-run',
    name: 'Rescue Run',
    kind: 'rescue',
    symbol: '◎',
    difficulty: 'Medium',
    description: 'Turn back, match the drift, and hold beside a person-overboard marker.',
    instructions:
      'Keep the marker 4–12 m to either side and within 5 m of midships. Hold for 6 seconds at no more than 0.5 kn relative speed, with the engine in neutral. Keep the hull clear.',
    locationId: 'haven',
    engine: true,
    conditions: { windDirection: 315, windSpeed: 10, currentDirection: 90, currentSpeed: 0.4 },
    start: { x: 0, z: 550, heading: 0, speed: 2, sails: 0, mainHoist: 0, jibHoist: 0 },
    targets: [{ x: -55, z: 640, radius: 12 }],
    hold: 6,
    goldTime: 150,
    silverTime: 240,
    timeLimit: 600,
    chart: { center: { x: 0, z: 600 }, span: 430 },
  },
  {
    id: 'treasure-chart',
    name: 'Treasure Chart',
    kind: 'treasure',
    symbol: '⌖',
    difficulty: 'Medium',
    description: 'Follow three bearing clues to uncover a hidden island cache.',
    instructions:
      'Sail within 22 m of each hidden location in order. Bearings and distances are measured from the start or the previous discovery. Revealing a target costs 10 points per clue.',
    locationId: 'haven',
    engine: false,
    conditions: { windDirection: 180, windSpeed: 14, currentDirection: 90, currentSpeed: 0 },
    start: { x: 0, z: 450, heading: 39, speed: 2 },
    targets: [
      { x: 160, z: 250, radius: 22, clue: 'Search west of Little Haven.' },
      { x: 60, z: 0, radius: 22, clue: 'Continue into the open water between the islands.' },
      { x: -120, z: -120, radius: 22, clue: 'The cache lies southeast of Pine Island.' },
    ],
    goldTime: 330,
    silverTime: 500,
    timeLimit: 900,
    chart: { center: { x: 0, z: 80 }, span: 1250 },
  },
  {
    id: 'anchor-bullseye',
    name: 'Anchor Bullseye',
    kind: 'anchor',
    symbol: '⚓',
    difficulty: 'Medium',
    description: 'Choose your drop point and settle the yacht inside a small anchoring circle.',
    instructions:
      'Settle within the 22 m circle for 10 seconds at no more than 0.25 kn over ground. Lower both sails, select neutral, and deploy at least 4:1 scope. The anchor must touch bottom and payout must finish.',
    locationId: 'shelter',
    engine: true,
    conditions: { windDirection: 270, windSpeed: 8, currentDirection: 90, currentSpeed: 0.6 },
    start: {
      x: 175,
      z: 335,
      heading: 0,
      speed: 0,
      sails: 0,
      mainHoist: 0,
      jibHoist: 0,
      anchorRode: 65,
    },
    targets: [{ x: 235, z: 230, radius: 22 }],
    hold: 10,
    goldTime: 360,
    silverTime: 540,
    timeLimit: 900,
    chart: { center: { x: 210, z: 270 }, span: 350 },
  },
  {
    id: 'shallow-shortcut',
    name: 'The Shallow Shortcut',
    kind: 'passage',
    symbol: '≋',
    difficulty: 'Hard',
    description: 'Take the narrow inner passage or the longer deep-water route around Pine Island.',
    instructions:
      'Reach the finish north of Pine Island while keeping at least 1 m beneath the keel across the hull. The chart shows two optional routes. The inner passage is shorter and shallower.',
    locationId: 'haven',
    engine: true,
    conditions: { windDirection: 90, windSpeed: 10, currentDirection: 90, currentSpeed: 0.2 },
    start: { x: -320, z: 60, heading: 48, speed: 0, sails: 0, mainHoist: 0, jibHoist: 0 },
    targets: [{ x: -300, z: -760, radius: 28 }],
    clearance: 1,
    alternatives: [
      {
        name: 'Inner passage',
        points: [
          { x: -320, z: 60 },
          { x: -100, z: -140 },
          { x: -85, z: -280 },
          { x: -55, z: -380 },
          { x: -80, z: -500 },
          { x: -300, z: -760 },
        ],
      },
      {
        name: 'Outer passage',
        points: [
          { x: -320, z: 60 },
          { x: -660, z: -100 },
          { x: -740, z: -370 },
          { x: -700, z: -560 },
          { x: -300, z: -760 },
        ],
      },
    ],
    goldTime: 480,
    silverTime: 650,
    timeLimit: 1200,
    chart: { center: { x: -380, z: -330 }, span: 1450 },
  },
  {
    id: 'one-tack-wonder',
    name: 'One-Tack Wonder',
    kind: 'tack',
    symbol: '⋀',
    difficulty: 'Hard',
    description: 'Pick your turning point and reach an upwind finish with exactly one tack.',
    instructions:
      'Cross the wind once, then establish the new tack for 2 seconds with sails raised and at least 0.5 kn through the water. Reach the finish with exactly one tack. A second tack or a gybe ends the attempt.',
    locationId: 'haven',
    engine: false,
    conditions: { windDirection: 0, windSpeed: 15, currentDirection: 90, currentSpeed: 0 },
    start: { x: 0, z: 1080, heading: 52, speed: 2 },
    targets: [{ x: 0, z: 750, radius: 25 }],
    goldTime: 260,
    silverTime: 400,
    timeLimit: 900,
    chart: { center: { x: 100, z: 920 }, span: 650 },
  },
  APPARENT_WIND_LAB,
];

export function getChallenge(id) {
  const challenge = CHALLENGES.find((item) => item.id === id);
  if (!challenge) throw new RangeError('Unknown challenge');
  return challenge;
}
