import {getLanguage,translate as t,translatedScenario} from '../i18n/runtime.js';
import {beginDecision,tickDecision,inspectDecision,setDecisionValue,submitDecision,endDecision,decisionScore,decisionReport} from './decision-engine.js';
import {createScenarioVisual} from './scenario-visual.js';
import {decisionDebriefReason,decisionEvidenceMarkup} from './decision-debrief.js';
import './scenario-visual.css';
import './decision-ui.css';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=value=>esc(t(value));
export function createDecisionTraining({onResult,onClose=()=>{},onStudy,onGuide}){
 const root=document.createElement('main');root.id='decision-training';root.className='decision-training';root.hidden=true;root.dataset.noTranslate='true';document.querySelector('.topbar').after(root);
 let canonical,scenario,attempt,visual,opener,returnScroll=0,notice='',recorded=false,suspended=false;
 const $=s=>root.querySelector(s);
 function persist(){if(!recorded&&attempt?.status!=='active'){onResult(decisionReport(attempt,canonical));recorded=true;}}
 function close(){if(root.hidden&&!suspended)return;suspended=false;endDecision(attempt);persist();visual?.dispose();root.hidden=true;document.body.removeAttribute('data-training');document.querySelector('.workspace').hidden=false;document.querySelector('.bottom-bar').hidden=false;onClose();window.scrollTo(0,returnScroll);if(opener?.isConnected)opener.focus({preventScroll:true});}
 function suspend(){if(root.hidden)return;suspended=true;root.hidden=true;}
 function resume(){if(!suspended)return;suspended=false;root.hidden=false;document.querySelector('.workspace').hidden=true;document.querySelector('.bottom-bar').hidden=true;window.dispatchEvent(new Event('sail-training-open'));}
 function open(value){if(!root.hidden||suspended)close();canonical=value;scenario=translatedScenario(value);attempt=beginDecision(value);recorded=false;notice='';opener=document.activeElement;returnScroll=window.scrollY;document.querySelector('#modal').close();document.querySelector('.workspace').hidden=true;document.querySelector('.bottom-bar').hidden=true;root.hidden=false;document.body.dataset.training='true';window.dispatchEvent(new Event('sail-training-open'));render();window.scrollTo(0,0);$('#training-title').focus({preventScroll:true});}
 function updateVisual(){if(!visual||attempt.status!=='active')return;const stage=scenario.stages[attempt.index],valueLabels=Object.fromEntries(stage.fields.map(field=>{const value=attempt.values[field.id];return [field.id,Array.isArray(value)?value.map(id=>field.options?.find(o=>o.id===id)?.label??id).join(' → '):field.options?.find(o=>o.id===value)?.label??value];}));
  visual.update({scenarioId:scenario.id,stageId:stage.id,family:scenario.family,scene:stage.scene,facts:stage.facts,values:attempt.values,inspected:attempt.inspected,valueLabels,lang:getLanguage()});
  const status=$('#reports-status');if(status)status.textContent=`${t('Required reports')}: ${stage.requiredFacts.filter(id=>attempt.inspected.includes(id)).length} / ${stage.requiredFacts.length}`;
 }
 function fieldMarkup(field){const value=attempt.values[field.id],invalid=attempt.message?.fields?.includes(field.id),id=`training-field-${field.id}`;
  let control='';
  if(field.type==='select')control=`<select id="${id}" data-value="${esc(field.id)}" aria-invalid="${!!invalid}"><option value="">${label('Choose…')}</option>${field.options.map(o=>`<option value="${esc(o.id)}" ${value===o.id?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`;
  else if(field.type==='number')control=`<div class="training-number"><input id="${id}" data-value="${esc(field.id)}" type="number" inputmode="decimal" step="any" ${field.min!==undefined?`min="${field.min}"`:''} ${field.max!==undefined?`max="${field.max}"`:''} value="${esc(value??'')}" aria-invalid="${!!invalid}"><span>${esc(field.unit)}</span></div>`;
  else if(field.type==='checks')control=`<div class="training-checks">${field.options.map(o=>`<label><input type="checkbox" data-check="${esc(field.id)}" value="${esc(o.id)}" ${value?.includes(o.id)?'checked':''}><span>${esc(o.label)}</span></label>`).join('')}</div>`;
  else {const chosen=Array.isArray(value)?value:[];control=`<ol class="training-sequence">${chosen.map((item,index)=>`<li><span>${esc(field.options.find(o=>o.id===item)?.label)}</span><div>${index?`<button type="button" data-reorder="${esc(field.id)}" data-index="${index}" data-offset="-1" aria-label="${label('Move earlier')}">↑</button>`:''}${index<chosen.length-1?`<button type="button" data-reorder="${esc(field.id)}" data-index="${index}" data-offset="1" aria-label="${label('Move later')}">↓</button>`:''}<button type="button" data-remove="${esc(field.id)}" data-index="${index}" aria-label="${label('Remove')}">×</button></div></li>`).join('')}</ol><select id="${id}" data-add="${esc(field.id)}" aria-label="${label('Add to sequence')}: ${esc(field.label)}" aria-invalid="${!!invalid}"><option value="">${label('Add to sequence')}</option>${field.options.filter(o=>!chosen.includes(o.id)).map(o=>`<option value="${esc(o.id)}">${esc(o.label)}</option>`).join('')}</select>`;}
  return `<fieldset class="training-field ${invalid?'invalid':''}" data-field="${esc(field.id)}"><legend>${esc(field.label)}</legend>${control}</fieldset>`;
 }
 function bindFields(){root.querySelectorAll('[data-value]').forEach(input=>{input.setAttribute('aria-label',scenario.stages[attempt.index].fields.find(f=>f.id===input.dataset.value).label);input.oninput=()=>{setDecisionValue(attempt,canonical,input.dataset.value,input.value);input.setAttribute('aria-invalid','false');input.closest('fieldset').classList.remove('invalid');updateVisual();};});
  root.querySelectorAll('[data-check]').forEach(input=>input.onchange=()=>{const id=input.dataset.check,values=[...root.querySelectorAll('[data-check]')].filter(el=>el.dataset.check===id&&el.checked).map(el=>el.value);setDecisionValue(attempt,canonical,id,values);updateVisual();});
  root.querySelectorAll('[data-add]').forEach(input=>input.onchange=()=>{if(input.value)append(input.dataset.add,input.value);});
  root.querySelectorAll('[data-reorder]').forEach(button=>button.onclick=()=>{const id=button.dataset.reorder,values=[...attempt.values[id]],i=Number(button.dataset.index),j=i+Number(button.dataset.offset);[values[i],values[j]]=[values[j],values[i]];setDecisionValue(attempt,canonical,id,values);renderFields(id);});
  root.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{const id=button.dataset.remove,values=[...attempt.values[id]];values.splice(Number(button.dataset.index),1);setDecisionValue(attempt,canonical,id,values);renderFields(id);});
 }
 function renderFields(focus){$('#training-fields').innerHTML=scenario.stages[attempt.index].fields.map(fieldMarkup).join('');bindFields();updateVisual();if(focus)document.getElementById(`training-field-${focus}`)?.focus({preventScroll:true});}
 function append(id,value){const field=canonical.stages[attempt.index]?.fields.find(f=>f.id===id);if(!field||!['order','route'].includes(field.type)||!field.options.some(o=>o.id===value))return;const values=attempt.values[id]||[];if(!values.includes(value)){setDecisionValue(attempt,canonical,id,[...values,value]);renderFields(id);}}
 function feedback(){const kind=attempt.message?.kind;let message=kind==='incomplete'?t('Complete the marked fields and inspect the required reports.'):kind==='revision'?`${t('Revise the marked actions. −5 points.')} ${scenario.stages[attempt.index].retry}`:notice;$('#training-feedback').textContent=message;$('#training-feedback').classList.toggle('error',['incomplete','revision'].includes(kind));}
 function render(){visual?.dispose();visual=null;const active=attempt.status==='active';root.innerHTML=`<div class="training-shell"><div class="training-toolbar"><button id="training-close" class="training-button">${label(active?'End training':'Return to simulator')}</button><span class="training-kind">${label('Interactive seamanship')}</span><button id="training-study" class="training-button">${label('Study material')}</button></div><header class="training-heading"><div><div class="eyebrow">${label('Training goals')} · ${Math.min(attempt.index+1,scenario.stages.length)} / ${scenario.stages.length}</div><h1 id="training-title" tabindex="-1">${esc(scenario.title)}</h1></div><div class="training-score"><span>${label('Score')}</span><strong dir="ltr">${decisionScore(attempt,canonical)}<small> / 100</small></strong><span>${label('All goals + 80/100 + no critical failure')}</span></div></header><ol class="training-milestones">${scenario.stages.map((stage,i)=>`<li ${active&&i===attempt.index?'aria-current="step"':''} class="${i<attempt.index?'done':''}"><span>${i<attempt.index?'✓':i+1}</span><div>${esc(stage.title)}<small>${Math.floor(100/scenario.stages.length)+(i<100%scenario.stages.length?1:0)} / 100</small></div></li>`).join('')}</ol><div id="training-body"></div></div>`;
  $('#training-close').onclick=()=>{if(active){endDecision(attempt);persist();render();$('#training-title').focus();}else close();};$('#training-study').onclick=()=>{suspend();onStudy();};
  if(!active){renderDebrief();return;}
  const stage=scenario.stages[attempt.index];$('#training-body').innerHTML=`<div class="training-layout"><section><div id="training-visual"></div><p class="training-limits">${esc(scenario.limitations)}</p></section><section class="training-task"><div class="eyebrow">${label('Now')}</div><h2>${esc(stage.title)}</h2><p>${esc(stage.brief)}</p><p class="training-goal">${esc(stage.goal)}</p><p id="reports-status"></p><form id="training-form" novalidate><div id="training-fields"></div><p id="training-feedback" role="status" tabindex="-1"></p><button id="training-commit" class="training-button primary" type="submit">${label('Commit actions')}</button></form><div class="training-help"><button id="training-hint" class="training-button">${label('Show hint')}</button><button id="training-guide" class="training-button">${label('Explore this topic')}</button></div><p class="training-rules">${label('Each incorrect committed plan costs 5 points. Inspecting, editing and hints are free.')}</p></section></div>`;
  visual=createScenarioVisual($('#training-visual'),{lang:getLanguage(),onInspect:id=>{inspectDecision(attempt,canonical,id);updateVisual();},onAction:action=>{if(action.type==='append')append(action.fieldId,action.value);}});renderFields();feedback();
  $('#training-form').onsubmit=event=>{event.preventDefault();const previous=scenario.stages[attempt.index];const result=submitDecision(attempt,canonical);if(result.kind==='complete'){notice=`${t('Checkpoint complete')}. ${previous.success}`;persist();render();$('#training-title').focus({preventScroll:true});window.scrollTo(0,0);}else if(attempt.status!=='active'){persist();render();$('#training-title').focus();window.scrollTo(0,0);}else{renderFields();feedback();$('.training-score strong').innerHTML=`${decisionScore(attempt,canonical)}<small> / 100</small>`;$('#training-feedback').focus({preventScroll:true});$('#training-feedback').scrollIntoView({block:'nearest'});}};
  $('#training-hint').onclick=()=>{attempt.hints++;attempt.message=null;notice=`${stage.goal} ${stage.facts.map(f=>f.text).join(' ')}`;feedback();};$('#training-guide').onclick=()=>{attempt.hints++;onGuide();};
 }
 function renderDebrief(){const report=decisionReport(attempt,canonical),passed=attempt.status==='passed',failedStage=scenario.stages[attempt.index];
  const reason=decisionDebriefReason(report,scenario);
  $('#training-body').innerHTML=`<section class="training-debrief"><div class="eyebrow">${label('Training debrief')}</div><h2>${label(passed?'Training passed':'Training not passed')}</h2><p role="status">${esc(reason)}</p><p>${label('Training evidence saved.')}</p><ul class="training-results">${decisionEvidenceMarkup(report,scenario)}</ul><p>${label('Deductions')}: <b dir="ltr">−${report.penalties.reduce((sum,p)=>sum+p.points,0)}</b> · ${label('Revised decisions')}: ${attempt.mistakes}</p><p class="training-limits">${esc(scenario.limitations)}</p><div class="training-actions"><button id="training-retry" class="training-button primary">${label('Restart training')}</button><button id="training-finish" class="training-button">${label('Return to simulator')}</button></div></section>`;
  $('#training-retry').onclick=()=>open(canonical);$('#training-finish').onclick=close;
 }
 return {open,close,suspend,resume,get isOpen(){return !root.hidden||suspended;},get active(){return (!root.hidden||suspended)&&attempt?.status==='active';},tick(dt){if(!root.hidden)tickDecision(attempt,dt);}};
}
