import {LOCATIONS} from '../locations.js';
import {shoreScale} from '../rendering/geography.js';
import {translate as t} from '../i18n/runtime.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chart(location){const scale=240/location.chart.span,map=(x,z)=>[160+(x-location.chart.centerX)*scale,100+(z-location.chart.centerZ)*scale];return `<svg viewBox="0 0 320 200" role="img" aria-label="${esc(t('Fictional training chart'))}">${location.islands.map(i=>`<polygon fill="#718b72" stroke="#a9ba92" points="${Array.from({length:90},(_,n)=>{const a=n/90*Math.PI*2,r=shoreScale(a);return map(i.x+Math.cos(a)*i.rx*r,i.z+Math.sin(a)*i.rz*r).join(',');}).join(' ')}"/>`).join('')}${location.buoys.map(b=>{const [x,y]=map(b.x,b.z);return `<circle cx="${x}" cy="${y}" r="3" fill="#f0c884"/>`;}).join('')}<g transform="translate(${map(location.start.x,location.start.z).join(' ')})"><path d="M0 -7 5 6 0 3 -5 6Z" fill="#fff8df"/></g><text x="14" y="23" fill="#cfe0d9" font-size="12">N ↑</text></svg>`;}
export function openLocations({openModal,onSelect,isActive}){
 openModal(`<div class="eyebrow">${esc(t('Practice waters'))}</div><h2>${esc(t('Choose your sailing grounds.'))}</h2><p>${esc(t('Selecting a location resets the boat and conditions. Your course record is kept. Assessed practices use Haven Islands.'))}</p>${isActive?`<p class="training-notice">${esc(t('Finish or end the current practice before changing location.'))}</p>`:''}<div class="location-grid">${LOCATIONS.map(l=>`<article class="location-choice" data-location-card="${l.id}">${chart(l)}<h3>${esc(t(l.title))}</h3><p>${esc(t(l.description))}</p><div class="location-metadata"><span>${esc(t('Wind speed'))}: ${l.conditions.windSpeed} kn</span><span>${esc(t('Current speed'))}: ${l.conditions.currentSpeed} kn</span></div><button class="training-button primary" data-location="${l.id}" ${isActive?'disabled':''}>${esc(t('Sail here'))}</button></article>`).join('')}</div>`);
 document.querySelectorAll('[data-location]').forEach(button=>button.onclick=()=>{if(isActive)return;document.querySelector('#modal').close();onSelect(button.dataset.location);});
}
