import {drills,createDrillState,beginManeuver,advanceManeuver,cancelManeuver,maneuverTelemetry} from './maneuvers.js';
import {MANEUVER_STORAGE_KEY,createManeuverRecord,captureManeuver,finishManeuverRecord,restoreManeuverRecords,addManeuverRecord,sampleAtTime} from './maneuver-records.js';
import {translate as t} from '../i18n/runtime.js';
import './maneuver-ui.css';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=s=>esc(t(s)),fmt=(v,d=1)=>Number.isFinite(v)?v.toFixed(d):'—';
const $=s=>document.querySelector(s);
export function createManeuverLab({getState,onStart,onStop,onControl,openModal,openBriefing=openModal,setCues,onBuoyCourse,toast}){
 let attempt=null,record=null,history=[],lastIndex=-1,refresh=0,replayFrame=0,reviewGeneration=0;
 function stopReplay(){reviewGeneration++;cancelAnimationFrame(replayFrame);replayFrame=0;}
 $('#modal').addEventListener('close',stopReplay);
 try{history=restoreManeuverRecords(localStorage.getItem(MANEUVER_STORAGE_KEY),drills.map(d=>d.id));}catch{}
 const panel=document.createElement('section');panel.id='maneuver-live';panel.className='maneuver-live';panel.hidden=true;panel.setAttribute('aria-label',t('Maneuvering lab'));$('.simulator').append(panel);
 function persist(){try{localStorage.setItem(MANEUVER_STORAGE_KEY,JSON.stringify(history));}catch{toast(t('Recent attempts could not be saved. Keep this tab open to review your run.'));}}
 function library(){stopReplay();
  openModal(`<article class="maneuver-library"><div class="eyebrow">${tr('Maneuvering lab')}</div><h2>${tr('Engine skills, measured on the water.')}</h2><p>${tr('Three open-water drills connect throttle, momentum, and steering. Review your actual track and speed after every attempt.')}</p><div class="maneuver-drills">${drills.map((d,i)=>`<button data-drill="${d.id}"><span class="drill-number">0${i+1}</span><strong>${tr(d.title)}</strong><span>${tr(d.summary)}</span><b>→</b></button>`).join('')}</div><button class="training-button" id="lab-buoys">${tr('Buoy course')}</button><p>${tr('Return to the three-buoy sailing challenge.')}</p><h3>${tr('Recent attempts')}</h3><div class="maneuver-history">${history.length?history.map((r,i)=>`<button data-run="${i}"><span>${tr(drills.find(d=>d.id===r.drillId).title)}</span><small>${tr(r.status==='passed'?'Drill completed':'Attempt ended')} · <bdi>${fmt(r.samples.at(-1).t)} s</bdi></small><span>${tr('Review run')} →</span></button>`).join(''):`<p>${tr('No recorded attempts yet.')}</p>`}</div><p class="lab-note">${tr('Your six latest attempts are saved in this browser. Replays do not move the live boat or award course credit.')}</p></article>`);
  document.querySelectorAll('[data-drill]').forEach(b=>b.onclick=()=>briefing(b.dataset.drill));document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>review(history[+b.dataset.run]));$('#lab-buoys').onclick=()=>{leave();$('#modal').close();onBuoyCourse();};
 }
 function briefing(id){stopReplay();const d=drills.find(d=>d.id===id);
  openBriefing(`<article class="maneuver-briefing training-lesson"><div class="eyebrow">${tr('Drill briefing')}</div><h2>${tr(d.title)}</h2>${d.briefing.map(p=>`<p>${tr(p)}</p>`).join('')}<ol>${d.steps.map(s=>`<li>${tr(s.label)}</li>`).join('')}</ol><div class="lab-limit-grid"><span>${tr('Speed limit')}<bdi>${d.maxSpeed} kn</bdi></span><span>${tr('Practice area radius')}<bdi>${d.areaRadius} m</bdi></span>${d.limitAstern?`<span>${tr('Corridor half-width')}<bdi>${d.corridorHalfWidth} m</bdi></span><span>${tr('Astern stopping limit')}<bdi>${d.limitAstern} m</bdi></span>`:''}</div><p>${tr('Choose small throttle changes and watch speed through water. Use Neutral before reversing thrust.')}</p><p>${tr('Ahead or astern describes thrust; the yacht may still be moving in the opposite direction.')}</p><p class="training-notice">${tr('Starting a drill resets the boat to its prescribed position and conditions.')} ${tr('Training markers are visual targets, not obstacles.')}</p><div class="training-actions"><button id="begin-drill" class="training-button primary">${tr('Start this drill')}</button><button id="lab-back" class="training-button">${tr('Back to drills')}</button></div></article>`);
  $('#begin-drill').onclick=()=>start(id);$('#lab-back').onclick=library;
 }
 function start(id){stopReplay();cancel();onStart(createDrillState(id));attempt=beginManeuver(id,getState());record=createManeuverRecord(id,getState());lastIndex=-1;refresh=0;panel.hidden=false;$('#modal').close();renderLive();updateCues();}
 function renderLive(){const d=drills.find(d=>d.id===attempt.drillId);panel.innerHTML=`<div class="lab-live-top"><span class="eyebrow">${tr('Maneuvering lab')}</span><span id="lab-step" dir="auto"></span></div><h3>${tr(d.title)}</h3><p id="lab-objective"></p><div class="lab-hold"><span id="lab-hold-fill"></span></div><div class="lab-live-metrics"><span>${tr('Neutral dwell')} <bdi id="lab-neutral">0.0 / 0.4 s</bdi></span><span id="lab-distance"></span></div><div class="training-actions"><button id="lab-instructions" class="training-button">${tr('Drill briefing')}</button><button id="lab-end" class="training-button">${tr('End and review')}</button></div>`;$('#lab-instructions').onclick=()=>briefing(attempt.drillId);$('#lab-end').onclick=end;updateLive();}
 function updateLive(){if(!attempt||!$('#lab-objective'))return;const info=maneuverTelemetry(attempt,getState());$('#lab-objective').textContent=t(info.label);$('#lab-step').textContent=t('Step {number} of {total}').replace('{number}',Math.min(attempt.index+1,drills.find(d=>d.id===attempt.drillId).steps.length)).replace('{total}',drills.find(d=>d.id===attempt.drillId).steps.length);$('#lab-hold-fill').style.width=`${info.required?Math.min(100,attempt.held/info.required*100):0}%`;$('#lab-neutral').textContent=`${Math.min(.4,attempt.neutralHeld).toFixed(1)} / 0.4 s`;const value=info.distanceToTarget??(attempt.drillId==='engine-stop'?info.distance:info.asternDistance);$('#lab-distance').textContent=`${t(info.distanceToTarget!==null?'Distance to target':attempt.drillId==='engine-stop'?'Distance travelled':'Backed distance')}: ${fmt(value)} m`;}
 function updateCues(){if(!attempt)return;const d=drills.find(d=>d.id===attempt.drillId);setCues({...d.cues,showTrack:true,track:record.samples});}
 function finish(){onStop();finishManeuverRecord(record,attempt,getState());history=addManeuverRecord(history,record);persist();updateLive();}
 function cancel(){if(attempt?.status==='active'){cancelManeuver(attempt);finish();}}
 function end(){cancel();review(record);}
 function leave(){stopReplay();cancel();panel.hidden=true;setCues(null);}
 function tick(dt){if(attempt?.status!=='active')return;advanceManeuver(attempt,getState(),dt);captureManeuver(record,getState(),attempt.elapsed);refresh+=dt;if(refresh>=.2||attempt.index!==lastIndex){refresh=0;updateCues();updateLive();}if(attempt.status!=='active'){finish();review(record);}else if(attempt.index!==lastIndex&&lastIndex>=0)toast(t('The next checkpoint is ready.'));lastIndex=attempt.index;}
 function review(run){if(!run)return;stopReplay();const generation=reviewGeneration;const d=drills.find(d=>d.id===run.drillId),end=run.samples.at(-1).t,m=run.metrics;let time=end,playing=false,previous=0;
  const metrics=[['Time underway',end,'s'],['Travel after stop cue',m.entrySpeed==null?null:m.stopDistance,'m'],['Time after stop cue',m.entrySpeed==null?null:m.stopSeconds,'s'],['Speed at stop cue',m.entrySpeed,'kn'],['Maximum speed',m.peakSpeed,'kn'],['Maximum sternway',m.maxAstern,'kn'],['Heading change from start',m.maxHeadingError,'°'],['Cross-track error',m.maxCrossTrack,'m'],['Minimum depth',m.minDepth,'m'],...(m.gateCrossing?[['Speed at gate',m.gateCrossing.speed,'kn'],['Gate offset',m.gateCrossing.crossTrack,'m']]:[])];
  const feedback=m.overshoot>12?'The stopping zone was passed. Plan an earlier reduction in speed on the next attempt.':run.drillId==='engine-stop'&&m.maxAstern>.3?'The boat continued astern after the stopping cue. Try selecting neutral earlier as forward speed approaches zero.':'Compare the speed curve with your throttle changes. Momentum continues after neutral is selected.';
  openModal(`<article class="maneuver-review"><div class="eyebrow">${tr('Review your maneuver')}</div><h2>${tr(d.title)}</h2><div class="lab-result ${run.status==='passed'?'passed':'ended'}"><strong>${tr(run.status==='passed'?'Drill completed':'Attempt ended')}</strong><p>${tr(run.message)}</p></div><div class="lab-replay-grid"><figure><figcaption>${tr('Recorded track')}</figcaption><canvas id="lab-track" width="640" height="420" aria-label="${tr('Recorded track')}"></canvas></figure><figure><figcaption>${tr('Speed through water')}</figcaption><canvas id="lab-speed" width="640" height="420" aria-label="${tr('Speed through water')}"></canvas></figure></div><div class="lab-replay-controls"><button id="lab-replay-play" class="training-button">${tr('Play replay')}</button><label for="lab-replay-time">${tr('Replay time')} <bdi id="lab-replay-value"></bdi></label><input type="range" id="lab-replay-time" min="0" max="${end}" value="${end}" step="0.1" aria-label="${tr('Replay time')}"></div><p id="lab-replay-readings" class="lab-replay-readings" dir="ltr"></p><p class="lab-note">${tr('Recorded speed is signed: negative means moving astern. The track and chart remain north-up.')}</p><div class="lab-metrics-grid">${metrics.map(([key,val,unit])=>`<div><span>${tr(key)}</span><strong dir="ltr">${fmt(val)} <small>${unit}</small></strong></div>`).join('')}</div><p>${tr(feedback)}</p><div class="lab-event-list">${run.events.filter(e=>e.type==='checkpoint').map(e=>`<span>${tr('Checkpoint')} ${e.index+1} <bdi>${fmt(e.time)} s</bdi></span>`).join('')}</div><div class="training-actions"><button id="lab-retry" class="training-button primary">${tr('Retry same conditions')}</button><button id="lab-library" class="training-button">${tr('Back to drills')}</button></div><p class="lab-note">${tr('Your six latest attempts are saved in this browser. Replays do not move the live boat or award course credit.')}</p></article>`);
  function draw(){const {sample,index}=sampleAtTime(run.samples,time);$('#lab-replay-time').value=time;$('#lab-replay-value').textContent=`${fmt(time)} / ${fmt(end)} s`;$('#lab-replay-readings').textContent=`${fmt(sample.speed)} kn · ${String(Math.round(sample.heading)%360).padStart(3,'0')}° · ${t('Throttle')} ${Math.round(sample.throttle*100)}% · ${t('Helm angle')} ${fmt(sample.rudder,0)}°`;drawTrack($('#lab-track'),run,d,index);drawSpeed($('#lab-speed'),run,time);}
  $('#lab-replay-time').oninput=e=>{time=Number(e.target.value);draw();};$('#lab-replay-play').onclick=()=>{cancelAnimationFrame(replayFrame);playing=!playing;if(playing&&time>=end)time=0;$('#lab-replay-play').textContent=t(playing?'Pause replay':'Play replay');previous=0;if(playing)replayFrame=requestAnimationFrame(animate);};
  function animate(now){if(generation!==reviewGeneration||!$('#modal').open||!$('#lab-track')||!playing)return;if(previous)time=Math.min(end,time+(now-previous)/1000*4);previous=now;draw();if(time>=end){playing=false;$('#lab-replay-play').textContent=t('Play replay');}else replayFrame=requestAnimationFrame(animate);}
  $('#lab-retry').onclick=()=>{playing=false;cancelAnimationFrame(replayFrame);start(run.drillId);};$('#lab-library').onclick=()=>{playing=false;cancelAnimationFrame(replayFrame);library();};draw();
 }
 function mountChoices(target){
  target.innerHTML=`<details class="course-module" open><summary><span>${tr('Maneuvering lab')}</span><small>4</small></summary>${drills.map((d,i)=>`<button class="lesson-row" data-cover-drill="${d.id}"><span class="lesson-index">0${i+1}</span><span><strong>${tr(d.title)}</strong><small>${tr(d.summary)}</small></span></button>`).join('')}<button class="lesson-row" data-cover-buoys><span class="lesson-index">04</span><span><strong>${tr('Buoy course')}</strong><small>${tr('Return to the three-buoy sailing challenge.')}</small></span></button></details>`;
  target.querySelectorAll('[data-cover-drill]').forEach(button=>button.onclick=()=>briefing(button.dataset.coverDrill));
  target.querySelector('[data-cover-buoys]').onclick=()=>{
   openBriefing(`<section class="buoy-briefing"><div class="eyebrow">${tr('Buoy course')}</div><h2>${tr('Find your next mark.')}</h2><p>${tr('Three buoys. One beautiful passage.')}</p><p>${tr('Sail within 35 metres of each buoy in order. Use your chart to locate the next mark and keep clear of shallow water.')}</p><div class="training-actions"><button id="cover-start-buoys" class="training-button primary">${tr('Set sail')}</button></div></section>`);
   $('#cover-start-buoys').onclick=()=>{leave();onBuoyCourse();};
  };
 }
 return {mountChoices,library,briefing,start,tick,cancel,leave,end,review:()=>review(record),get active(){return attempt?.status==='active';},get current(){return attempt;},get chart(){if(!attempt)return null;const d=drills.find(d=>d.id===attempt.drillId);return {center:{x:d.origin.x,z:d.target?(d.origin.z+d.target.z)/2:d.origin.z+(d.limitAstern??0)/2},span:220,cues:d.cues};}};
}
function canvasBase(canvas){const c=canvas.getContext('2d');c.fillStyle='#0e2a35';c.fillRect(0,0,canvas.width,canvas.height);c.font=`${18*(Number(document.documentElement.dataset.textSize)||100)/100}px Arial`;c.lineWidth=1;return c;}
function drawTrack(canvas,run,d,index){const c=canvasBase(canvas),w=canvas.width,h=canvas.height,points=[...run.samples,d.origin];if(d.gate)points.push(d.gate);if(d.target)points.push({x:d.target.x-d.target.radius,z:d.target.z-d.target.radius},{x:d.target.x+d.target.radius,z:d.target.z+d.target.radius});const xs=points.map(p=>p.x),zs=points.map(p=>p.z),cx=(Math.min(...xs)+Math.max(...xs))/2,cz=(Math.min(...zs)+Math.max(...zs))/2,scale=Math.min((w-90)/Math.max(40,Math.max(...xs)-Math.min(...xs)),(h-85)/Math.max(40,Math.max(...zs)-Math.min(...zs)));const map=p=>[w/2+(p.x-cx)*scale,h/2+(p.z-cz)*scale];
 c.strokeStyle='#35525b';for(let x=40;x<w;x+=60){c.beginPath();c.moveTo(x,30);c.lineTo(x,h-30);c.stroke();}for(let y=30;y<h;y+=60){c.beginPath();c.moveTo(40,y);c.lineTo(w-30,y);c.stroke();}c.fillStyle='#b7d0ce';c.fillText('N ↑',20,25);
 if(d.gate){const [x,y]=map(d.gate);c.strokeStyle='#e5bc78';c.lineWidth=4;c.beginPath();c.moveTo(x-d.gate.halfWidth*scale,y);c.lineTo(x+d.gate.halfWidth*scale,y);c.stroke();}
 if(d.target){const [x,y]=map(d.target);c.strokeStyle='#93c5ae';c.lineWidth=2;c.beginPath();c.arc(x,y,d.target.radius*scale,0,Math.PI*2);c.stroke();}
 if(d.corridorHalfWidth){c.strokeStyle='#547d78';c.setLineDash([6,7]);for(const sign of [-1,1]){const a=map({x:d.origin.x+sign*d.corridorHalfWidth,z:d.origin.z}),b=map({x:d.origin.x+sign*d.corridorHalfWidth,z:d.origin.z+d.limitAstern});c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke();}c.setLineDash([]);}
 c.strokeStyle='#42616a';c.lineWidth=3;c.beginPath();run.samples.forEach((p,i)=>i?c.lineTo(...map(p)):c.moveTo(...map(p)));c.stroke();c.strokeStyle='#efc27d';c.beginPath();run.samples.slice(0,index+1).forEach((p,i)=>i?c.lineTo(...map(p)):c.moveTo(...map(p)));c.stroke();
 const s=run.samples[index],[x,y]=map(s);c.save();c.translate(x,y);c.rotate(s.heading*Math.PI/180);c.fillStyle='#f0f4e9';c.beginPath();c.moveTo(0,-12);c.lineTo(7,9);c.lineTo(0,5);c.lineTo(-7,9);c.closePath();c.fill();c.restore();const bar=Math.max(5,Math.round(70/scale/5)*5);c.strokeStyle='#b7d0ce';c.beginPath();c.moveTo(20,h-28);c.lineTo(20+bar*scale,h-28);c.stroke();c.fillStyle='#b7d0ce';c.fillText(`${bar} m`,20,h-5);
}
function drawSpeed(canvas,run,time){const c=canvasBase(canvas),w=canvas.width,h=canvas.height,p=45,end=Math.max(1,run.samples.at(-1).t),speeds=run.samples.map(s=>s.speed),min=Math.min(-.5,...speeds)-.2,max=Math.max(.5,...speeds)+.2,x=t=>p+t/end*(w-p*1.5),y=v=>h-p-(v-min)/(max-min)*(h-p*2);c.strokeStyle='#49606a';c.beginPath();c.moveTo(p,y(0));c.lineTo(w-p/2,y(0));c.stroke();c.fillStyle='#a9c3c5';for(const v of [min+.2,0,max-.2])c.fillText(`${fmt(v)} kn`,8,y(v)-6);c.fillText('0 s',p,h-10);c.textAlign='right';c.fillText(`${fmt(end,0)} s`,w-p/2,h-10);c.textAlign='left';
 c.setLineDash([5,7]);c.strokeStyle='#416571';for(const event of run.events){c.beginPath();c.moveTo(x(event.time),p);c.lineTo(x(event.time),h-p);c.stroke();}c.setLineDash([]);c.strokeStyle='#ebc88b';c.lineWidth=3;c.beginPath();run.samples.forEach((s,i)=>i?c.lineTo(x(s.t),y(s.speed)):c.moveTo(x(s.t),y(s.speed)));c.stroke();c.strokeStyle='#a4d7bc';c.lineWidth=1.5;c.beginPath();c.moveTo(x(time),p);c.lineTo(x(time),h-p);c.stroke();
}
