import {getLanguage,translate as t} from '../i18n/runtime.js';
import {renderTeachingFigure,getTeachingFigureCaption} from './teaching-figures.js';
import './reader.css';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=s=>esc(t(s));

// Navigation is study progress only. The existing assessment engine owns credit.
export function lessonPages(lesson){
 return [...lesson.concepts.map((text,index)=>({kind:'concept',index,text})),{kind:'observe'},...(lesson.practice?[{kind:'practice'}]:[]),...lesson.quiz.map((_,index)=>({kind:'question',index})),{kind:'takeaway'}];
}
export function createLessonReader({onCheck,onPractice,onCourse,onRecord,onNext,onGuide=()=>{},onFigure=()=>{},getEvidence,onClose=()=>{}}){
 const root=document.createElement('main');root.id='lesson-reader';root.hidden=true;root.className='lesson-reader';document.querySelector('.topbar').after(root);
 let lesson,pages=[],page=0,answers=[],checked=[],opener=null,returnScroll=0;
 const pageTitle=p=>p.kind==='concept'?'Understand':p.kind==='observe'?'Look for this aboard':p.kind==='practice'?'Your practice checklist':p.kind==='question'?'Check your understanding':'Take this onto the water';
 function remember(){try{sessionStorage.setItem(`sail-reader-${lesson.id}`,String(page));}catch{}}
 function close(){if(root.hidden)return;root.hidden=true;document.body.removeAttribute('data-reading');document.querySelector('.workspace').hidden=false;window.scrollTo(0,returnScroll);if(opener?.isConnected)opener.focus({preventScroll:true});onClose();}
 function navigate(next){page=Math.max(0,Math.min(pages.length-1,next));remember();render();window.scrollTo(0,0);root.querySelector('#reader-step-title').focus({preventScroll:true});}
 function render(){
  const p=pages[page],e=getEvidence(),q=p.kind==='question'?lesson.quiz[p.index]:null;
  const sections=[['concept','Understand'],['observe','Observe'],...(lesson.practice?[['practice','Your practice checklist']]:[]),['question','Questions'],['takeaway','Takeaway']];
  let content='';
  if(p.kind==='concept')content=`<p class="reader-concept">${esc(p.text)}</p>`;
  if(p.kind==='observe')content=`<ol class="reader-observations">${lesson.observe.map((text,i)=>`<li><span aria-hidden="true">${i+1}</span><p>${esc(text)}</p></li>`).join('')}</ol><aside class="reader-mistake"><strong>${label('Common mistake')}</strong><p>${esc(lesson.mistake)}</p></aside>`;
  if(p.kind==='practice')content=`<ol class="reader-observations">${lesson.practice.steps.map((s,i)=>`<li><span aria-hidden="true">${i+1}</span><p>${esc(s.label)}${s.duration?`<small>${label('{seconds} s continuous').replace('{seconds}',s.duration)}</small>`:''}</p></li>`).join('')}</ol><p class="reader-small">${label('Begin practice resets your position, sails, helm, and weather. Timers run only while underway and restart if the condition is lost. Grounding, engine use, early anchoring, or changing conditions ends the attempt.')}</p><button id="begin-assessment" class="reader-button primary">${label(e.trainingActive?'Resume training':'Prepare simulation')}</button>`;
  if(q)content=`<form id="knowledge-form"><fieldset class="knowledge-question"><legend>${esc(q.prompt)}</legend>${q.options.map((text,i)=>`<label><input type="radio" name="q${p.index}" value="${i}" ${answers[p.index]===i?'checked':''} required><span>${esc(text)}</span></label>`).join('')}</fieldset><button class="reader-button primary" type="submit">${label('Check answer')}</button><div id="answer-${p.index}" class="answer-explanation ${checked[p.index]?(answers[p.index]===q.correct?'correct':'incorrect'):''}" role="status" ${checked[p.index]?'':'hidden'}>${checked[p.index]?`${label(answers[p.index]===q.correct?'Correct.':'Review and try again.')} ${esc(q.explanation)}`:''}</div><p id="quiz-result" role="status">${e.knowledge?label('Knowledge check passed.'):''}</p></form>`;
  if(p.kind==='takeaway')content=`<p class="reader-concept">${esc(lesson.transfer)}</p><div class="reader-evidence"><span>${e.knowledge?'✓':'○'} ${label('Knowledge check')}</span><span>${(lesson.practice?e.practice:e.decision)?'✓':'○'} ${label(lesson.practice?'Live boat handling':'Interactive seamanship')}</span></div>${!e.ready?`<p class="reader-small">${label('Study is open. Complete earlier lessons for sequential course mastery.')}</p>`:''}${lesson.practice&&e.practice?`<aside class="reader-mistake"><strong>${label('Practice debrief')}</strong><p>${esc(lesson.practice.debrief)}</p></aside>`:''}<div class="reader-actions">${lesson.practice?`<button id="begin-assessment" class="reader-button primary">${label(e.trainingActive?'Resume training':'Prepare simulation')}</button>`:`<button id="reader-next-lesson" class="reader-button primary">${label('Browse next lesson →')}</button>`}<button id="reader-record" class="reader-button">${label('My course record')}</button></div><p class="reader-small">${label('Simulator achievement is a study record, not a sailing qualification. Learn physical procedures and local rules with a qualified instructor.')}</p>`;
  root.innerHTML=`<div class="reader-shell"><div class="reader-toolbar"><button id="reader-close" class="reader-button">${label('Return to simulator')}</button><span class="reader-paused">${label('Text lesson')} · ${label('Read and explore. Simulation is paused.')}</span><button id="reader-start-training" class="reader-button primary">▶ ${label(e.trainingActive?'Resume training':'Start training')}</button><button id="reader-course" class="reader-button">${label('Course')}</button></div><header class="reader-heading"><div class="eyebrow">${label('Text lesson')} · ${label('LESSON')} ${Number(lesson.id.split('-')[1])} · ${lesson.minutes} ${label('MIN')}</div><h1>${esc(lesson.title)}</h1></header><nav class="reader-sections" aria-label="${label('Lesson sections')}">${sections.map(([kind,name])=>`<button data-reader-section="${kind}" ${p.kind===kind?'aria-current="step"':''}>${label(name)}</button>`).join('')}</nav><div class="reader-layout"><figure class="reader-figure">${renderTeachingFigure(lesson,getLanguage())}<figcaption>${esc(getTeachingFigureCaption(lesson,getLanguage()))}</figcaption><button id="reader-enlarge" class="reader-button">${label('Enlarge diagram')}</button></figure><article class="reader-page" data-page-kind="${p.kind}"><div class="reader-page-kicker">${label('Step {number} of {total}').replace('{number}',page+1).replace('{total}',pages.length)}${q?` · ${label('Question {number} of {total}').replace('{number}',p.index+1).replace('{total}',lesson.quiz.length)}`:''}</div><h2 id="reader-step-title" tabindex="-1">${label(pageTitle(p))}</h2>${content}<div class="reader-topic-action"><button id="reader-guide" class="reader-button">${label('Explore this topic')}</button></div></article></div><footer class="reader-navigation"><button id="reader-back" class="reader-button" ${page===0?'disabled':''}>${label('Back')}</button><div class="reader-progress"><span dir="ltr">${page+1} / ${pages.length}</span><progress value="${page+1}" max="${pages.length}" aria-label="${label('Reading progress')}"></progress></div><button id="reader-next" class="reader-button primary">${label(page===pages.length-1?'Return to simulator':q&&!checked[p.index]?'Skip for now':'Continue')}</button></footer></div>`;
  root.querySelector('#reader-start-training').onclick=()=>{close();onPractice();};root.querySelector('#reader-close').onclick=close;root.querySelector('#reader-course').onclick=()=>{close();onCourse();};root.querySelector('#reader-guide').onclick=()=>onGuide(lesson);root.querySelector('#reader-enlarge').onclick=()=>onFigure(lesson);
  root.querySelectorAll('[data-reader-section]').forEach(b=>b.onclick=()=>navigate(pages.findIndex(x=>x.kind===b.dataset.readerSection)));
  root.querySelector('#reader-back').onclick=()=>navigate(page-1);root.querySelector('#reader-next').onclick=()=>page===pages.length-1?close():navigate(page+1);
  if(root.querySelector('#begin-assessment'))root.querySelector('#begin-assessment').onclick=()=>{close();onPractice();};
  if(root.querySelector('#reader-record'))root.querySelector('#reader-record').onclick=()=>{close();onRecord();};
  if(root.querySelector('#reader-next-lesson'))root.querySelector('#reader-next-lesson').onclick=onNext;
  if(q){const form=root.querySelector('form');form.onchange=event=>{answers[p.index]=Number(event.target.value);checked[p.index]=false;root.querySelector(`#answer-${p.index}`).hidden=true;};form.onsubmit=event=>{event.preventDefault();const value=new FormData(form).get(`q${p.index}`);if(value===null)return;answers[p.index]=Number(value);checked[p.index]=true;const result=onCheck(answers.map((a,i)=>checked[i]?a:null),p.index);render();const feedback=root.querySelector(`#answer-${p.index}`);feedback.tabIndex=-1;feedback.focus({preventScroll:true});feedback.scrollIntoView({block:'nearest',behavior:'smooth'});if(result?.complete)root.querySelector('#quiz-result').textContent=t(result.correct?'Knowledge check passed.':'Review the explanations, change your answers, and check again.');};}
 }
 return {get isOpen(){return !root.hidden;},close,open(value){opener=root.hidden?document.activeElement:opener;if(root.hidden)returnScroll=window.scrollY;lesson=value;pages=lessonPages(lesson);answers=lesson.quiz.map(()=>null);checked=lesson.quiz.map(()=>false);try{const saved=Number(sessionStorage.getItem(`sail-reader-${lesson.id}`));page=Number.isInteger(saved)?Math.max(0,Math.min(pages.length-1,saved)):0;}catch{page=0;}document.querySelector('#modal').close();document.querySelector('.workspace').hidden=true;root.hidden=false;document.body.dataset.reading='true';window.dispatchEvent(new Event('sail-reader-open'));render();window.scrollTo(0,0);root.querySelector('#reader-step-title').focus({preventScroll:true});}};
}
