import { chromium,expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-webgl']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.setDefaultTimeout(60000);
const errors=[],consoleErrors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
const url=process.env.SAIL_URL||'http://127.0.0.1:5187';
try {
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:120000});
 await page.waitForFunction(()=>document.querySelector('#scene')?.dataset.drawCalls&&document.querySelector('#wind-arrow')?.style.transform,{timeout:120000});
 assert.match(await page.title(),/SAIL/);
 await page.screenshot({path:'artifacts/sail-desktop.png',fullPage:true,timeout:90000});
 // Knowledge feedback, actual mastery, and freely browsable prerequisite previews.
 await page.locator('#lesson-briefing').click();
 await expect(page.locator('#lesson-reader')).toBeVisible();
 await expect(page.locator('#modal')).not.toBeVisible();
 await page.screenshot({path:'artifacts/sail-lesson.png',fullPage:true,timeout:90000});
 await page.locator('[data-reader-section="question"]').click();
 await page.locator('input[name="q0"][value="0"]').check();
 await page.locator('#knowledge-form button[type="submit"]').click();
 await expect(page.locator('#answer-0')).toContainText('Review');
 assert.equal(await page.locator('#progress-label').textContent(),'0 / 42');
 await page.locator('input[name="q0"][value="1"]').check();
 await page.locator('#knowledge-form button[type="submit"]').click();
 await page.locator('#reader-next').click();
 await page.locator('input[name="q1"][value="1"]').check();
 await page.locator('#knowledge-form button[type="submit"]').click();
 await expect(page.locator('#quiz-result')).toContainText('passed');
 assert.equal(await page.locator('#progress-label').textContent(),'0 / 42','Knowledge alone must not award new scenario evidence');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sail-training-v1')).records['sail-01'].wrongAnswers),1);
 await page.locator('#reader-close').click();
 await page.waitForFunction(()=>Number(document.querySelector('#scene').dataset.triangles)>10000,{timeout:60000});
 await page.locator('#course-library').click();
 assert.equal(await page.locator('[data-library-lesson]').count(),42);
 await page.locator('[data-library-lesson="3"]').click();
 await page.locator('#practice-start').click();
 await expect(page.locator('#lesson-reader')).toBeHidden();
 await page.locator('button[data-camera="deck"]').click();
 await expect(page.locator('#objective-text')).toContainText('chart',{timeout:60000});
 await page.locator('#chart-toggle').click();await expect(page.locator('#large-chart')).toBeVisible();await page.locator('#close-modal').click();
 await expect(page.locator('.practice-debrief')).toContainText('Training passed',{timeout:60000});await page.locator('#close-modal').click();
 assert.equal(await page.locator('#progress-label').textContent(),'0 / 42','Practice preview alone does not award mastery');
 // Reset, real controls, and keyboard operation after a focused button.
 await page.locator('[data-mode="explore"]').click();
 await page.locator('button[data-camera="chase"]').click();
 await page.locator('#reset').click();await page.locator('#play').click();
 await page.keyboard.down('ArrowRight');
 await page.waitForFunction(()=>Number(document.querySelector('#rudder').value)>1,{timeout:60000});
 await page.keyboard.up('ArrowRight');await page.keyboard.press('c');
 await expect(page.locator('#rudder')).toHaveValue('0');
 await page.waitForFunction(()=>Number(document.querySelector('#speed').textContent)>.05,{timeout:60000});
 // Simulate the browser visibility signal: background time must not sail or earn practice credit.
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
 await expect(page.locator('#play')).toContainText('Set sail');
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
 await page.locator('#play').click();
 await page.locator('#systems-toggle').click();
 await page.locator('#vessel-mainHoist').fill('0.5');await page.locator('#vessel-jibHoist').fill('0');
 await page.locator('#sails').click();
 await expect(page.locator('#vessel-mainHoist')).toHaveValue('0');await expect(page.locator('#vessel-jibHoist')).toHaveValue('0');
 await page.locator('#vessel-mainHoist').fill('0.5');await page.locator('#vessel-jibHoist').fill('1');
 await page.locator('#vessel-jibSheet').fill('55');await page.locator('#vessel-reefLevel').selectOption('2');await page.locator('#vessel-traveler').fill('10');await page.locator('#vessel-vang').fill('0.75');await page.locator('#vessel-outhaul').fill('0.8');
 await expect(page.locator('#reef span')).toHaveText('Reef 2');
 await page.locator('button[data-camera="deck"]').click();
 await page.waitForFunction(()=>document.querySelector('#scene').dataset.camera==='deck');
 await page.screenshot({path:'artifacts/sail-systems.png',fullPage:true,timeout:90000});
 await page.locator('#systems-close').click();await page.locator('#sails').click();
 await page.locator('#systems-toggle').click();
 await page.getByText('Engine & close quarters',{exact:true}).click();
 await page.locator('#vessel-throttle').fill('-0.7');await expect(page.locator('[data-system-status]')).toContainText('astern');
 await page.locator('[data-command="neutral"]').click();await expect(page.locator('#vessel-throttle')).toHaveValue('0');
 await page.getByText('Anchor & holding',{exact:true}).click();await page.locator('#vessel-anchorRode').fill('140');await page.locator('[data-command="anchor"]').click();await expect(page.locator('#anchor span')).toHaveText('Weigh anchor');
 await page.locator('[data-command="anchor"]').click();await page.locator('#systems-close').click();
 await page.locator('#conditions').click();await page.locator('#wind-speed').fill('20');await page.locator('#current-speed').fill('1.5');await page.locator('#current-direction').fill('90');await page.locator('#close-modal').click();
 await expect(page.locator('#weather-wind')).toContainText('20 kn');
 await page.locator('#reset').click();
 await page.locator('button[data-camera="helm"]').click();await page.waitForFunction(()=>document.querySelector('#scene').dataset.camera==='helm');await page.waitForTimeout(2200);await page.screenshot({path:'artifacts/sail-helm.png',fullPage:true,timeout:90000});
 await page.locator('button[data-camera="deck"]').click();await page.waitForFunction(()=>document.querySelector('#scene').dataset.camera==='deck');await page.waitForTimeout(2200);await page.screenshot({path:'artifacts/sail-cockpit.png',fullPage:true,timeout:90000});
 await page.locator('button[data-camera="chase"]').click();
 // Saved knowledge/practice restore without claiming interrupted practice continuity.
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#scene')?.dataset.drawCalls,{timeout:120000});
 assert.equal(await page.locator('#progress-label').textContent(),'0 / 42');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('sail-training-v1')));assert.equal(saved.records['sail-04'].practice,true);
 // Mobile access to the course, detailed systems, and normal controls.
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(2200);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal mobile overflow');
 await page.screenshot({path:'artifacts/sail-mobile.png',fullPage:true,timeout:90000});
 await page.locator('[data-mode="learn"]').click();await expect(page.locator('[data-library-lesson="0"]')).toBeVisible();await page.locator('#close-modal').click();
 await page.locator('#systems-toggle').click();await page.locator('#vessel-mainHoist').fill('0.25');await page.locator('#systems-close').click();
 await page.locator('#sails').click();await page.locator('#reef').click();await page.locator('#help').click();await expect(page.locator('#modal')).toBeVisible();await page.locator('#close-modal').click();
 await page.goto(new URL('/reference/esail/index.html',url).href,{waitUntil:'domcontentloaded'});await page.locator('#search').fill('reefing');assert.ok(await page.locator('#results article').count()>0);await page.locator('#images').click();await page.locator('#search').fill('');assert.equal(await page.locator('#results .image').count(),234);
 assert.deepEqual(errors,[],'No uncaught browser errors');
 assert.equal(consoleErrors.filter(s=>/Shader Error|VALIDATE_STATUS|Error creating WebGL|THREE.WebGLProgram/.test(s)).length,0,'No shader or WebGL errors');
 await writeFile('artifacts/browser-check.json',JSON.stringify({passed:true,errors,consoleErrors,checkedAt:new Date().toISOString(),features:['lesson feedback','mastery','42-lesson library','ordered practice','persistence','keyboard helm','tab visibility pause','independent sails','reef levels','traveler','vang','outhaul','engine neutral/astern','anchor rode','current','cameras','mobile','archive']},null,2));
 console.log('Full browser checks passed: training, controls, cameras, mobile, and archive.');
}finally{await browser.close();}
