import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-webgl']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')console.log('Browser console:',m.text());});
await page.goto(process.env.SAIL_URL || 'http://127.0.0.1:5187',{waitUntil:'domcontentloaded'});
await page.waitForTimeout(1500);
console.log('Page loaded:',await page.title(),errors);
await page.waitForSelector('#scene canvas');
await page.waitForTimeout(2200);
await page.screenshot({path:'artifacts/sail-desktop.png',fullPage:true});
await page.locator('#play').click();
await page.keyboard.down('ArrowRight');
await page.waitForTimeout(400);
await page.keyboard.up('ArrowRight');
assert.ok(Number(await page.locator('#rudder').inputValue())>0,'Keyboard steering works after starting');
await page.keyboard.press('c');
assert.equal(await page.locator('#rudder').inputValue(),'0');
await page.waitForTimeout(1500);
assert.ok(Number(await page.locator('#speed').textContent())>0,'Boat should move');
await page.locator('#conditions').click();
await page.locator('#wind-speed').fill('20');
await page.locator('#close-modal').click();
await page.waitForTimeout(200);
assert.match(await page.locator('#weather-wind').textContent(),/20 kn/);
await page.locator('#chart-toggle').click();
assert.equal(await page.locator('#large-chart').isVisible(),true);
await page.locator('#close-modal').click();
await page.locator('[data-mode="challenge"]').click();
assert.match(await page.locator('#card-title').textContent(),/three amber buoys/);
await page.locator('[data-mode="explore"]').click();
assert.match(await page.locator('#scene-heading').textContent(),/curiosity/);
await page.locator('[data-mode="learn"]').click();
await page.locator('[data-camera="helm"]').click();
await page.waitForTimeout(1600);
await page.screenshot({path:'artifacts/sail-helm.png',fullPage:true});
await page.locator('[data-camera="deck"]').click();
await page.waitForTimeout(1600);
assert.equal(await page.locator('#scene').getAttribute('data-camera'),'deck');
await page.screenshot({path:'artifacts/sail-cockpit.png',fullPage:true});
console.log('Rendering diagnostics:',await page.locator('#scene').evaluate(el=>({...el.dataset})));
await page.locator('[data-camera="chase"]').click();
await page.locator('#sails').click();
assert.match(await page.locator('#sails').textContent(),/Raise sails/);
await page.locator('#anchor').click();
assert.match(await page.locator('#anchor').textContent(),/Weigh anchor/);
await page.locator('#reset').click();
assert.equal(await page.locator('#heading').textContent(),'035');
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(4400);
await page.screenshot({path:'artifacts/sail-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile should not overflow horizontally');
await page.locator('#sails').click();
await page.locator('#reef').click();
await page.locator('#help').click();
assert.equal(await page.locator('#modal').isVisible(),true);
await page.locator('#close-modal').click();
await page.goto(new URL('/reference/esail/index.html',process.env.SAIL_URL || 'http://127.0.0.1:5187').href);
await page.locator('#search').fill('reefing');
assert.ok(await page.locator('#results article').count()>0,'Archive text search should find sailing topics');
await page.locator('#images').click();
await page.locator('#search').fill('');
assert.equal(await page.locator('#results .image').count(),234);
assert.deepEqual(errors,[]);
console.log('Browser checks passed: 3D rendering, sailing, weather, chart, modes, cameras, sails, anchor, reset, mobile controls, help, archive text search and 234-image gallery.');
await browser.close();
