"""Build an offline, searchable index of collected pages and images."""
from pathlib import Path
import json

root = Path(__file__).resolve().parents[1] / 'reference' / 'esail'
manifest = json.loads((root / 'manifest.json').read_text())
for page in manifest['pages']:
    page['text'] = (root / page['text_file']).read_text()
data = json.dumps(manifest, ensure_ascii=False).replace('<', '\\u003c')
html = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>eSail reference archive</title>
<style>*{box-sizing:border-box}body{margin:0;background:#102b36;color:#dfe9e6;font:15px/1.6 system-ui,sans-serif}header{padding:35px max(24px,6vw);border-bottom:1px solid #ffffff20}h1{font-size:32px;font-weight:500;margin:0}p{color:#a6bec3}input{background:#1c414d;border:1px solid #ffffff30;border-radius:6px;padding:14px;color:white;width:min(600px,100%);font:inherit}nav{display:flex;gap:12px;margin-top:18px}button{background:#244653;color:#c8d9dc;border:1px solid #ffffff20;padding:9px 18px;border-radius:4px;cursor:pointer}button.active{background:#ecc78e;color:#183641}main{padding:30px max(24px,6vw)}article{border-bottom:1px solid #ffffff20;padding:16px 0}summary{cursor:pointer;font-size:17px;color:#ecc78e}pre{white-space:pre-wrap;font:14px/1.8 system-ui,sans-serif;max-width:1000px}a{color:#ecc78e}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:18px}.image{border:1px solid #ffffff20;border-radius:8px;padding:12px;background:#173641}.image img{width:100%;height:160px;object-fit:contain;background:#f1efe5;border-radius:4px}.image span{display:block;font-size:12px;overflow-wrap:anywhere;margin-top:9px}#count{color:#a4bfc4}small{display:block;line-height:1.6;max-width:1000px;color:#8ba6ae}</style>
<header><h1>eSail reference archive</h1><p id="stats"></p><input id="search" type="search" aria-label="Search archive" placeholder="Search page text, image names, or descriptions…"><nav><button id="pages" class="active">Pages & text</button><button id="images">Images</button></nav><p id="count"></p><small id="scope"></small></header><main id="results"></main>
<script id="archive-data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('archive-data').textContent);let mode='pages';const $=s=>document.querySelector(s);$('#stats').textContent=`${data.pages.length} pages · ${data.images.length} images · ${data.errors.length} unavailable image references`;$('#scope').textContent=data.scope;
function render(){const query=$('#search').value.toLowerCase(),results=$('#results');results.replaceChildren();results.className=mode==='images'?'grid':'';const items=data[mode].filter(item=>(mode==='pages'?item.title+' '+item.text:item.url+' '+item.alt).toLowerCase().includes(query));$('#count').textContent=`${items.length} ${mode} found`;
for(const item of items){if(mode==='pages'){const article=document.createElement('article'),details=document.createElement('details'),summary=document.createElement('summary'),link=document.createElement('a'),pre=document.createElement('pre');summary.textContent=item.title;link.textContent=item.url;link.href=item.url;link.target='_blank';link.rel='noreferrer';pre.textContent=item.text;details.append(summary,link,pre);article.append(details);results.append(article);}else{const card=document.createElement('a'),img=document.createElement('img'),label=document.createElement('span');card.className='image';card.href=item.file;card.target='_blank';img.src=item.file;img.alt=item.alt||'Archived eSail image';img.loading='lazy';label.textContent=item.alt||item.file.split('/').pop();card.append(img,label);results.append(card);}}}
$('#search').oninput=render;['pages','images'].forEach(name=>$('#'+name).onclick=()=>{mode=name;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.id===name));render();});render();</script></html>'''
(root / 'index.html').write_text(html.replace('__DATA__', data))
print('Created reference/esail/index.html')
