import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const browser = await chromium.launch({headless:true, args:['--use-angle=swiftshader','--enable-webgl']});
const page = await browser.newPage({viewport:{width:390,height:844}, isMobile:true, hasTouch:true});
page.setDefaultTimeout(90000);
const errors=[];
page.on('pageerror', error=>errors.push(error.message));
const results=[];
await mkdir('artifacts/mobile', {recursive:true});
async function inspect(name, width, height) {
  await page.setViewportSize({width,height});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth),{timeout:10000}).toBeLessThanOrEqual(width+1);
  await page.evaluate(()=>window.scrollTo(0,0));
  const frames=await page.locator('#scene').getAttribute('data-frames');
  await page.waitForFunction(before=>Number(document.querySelector('#scene').dataset.frames)>Number(before)+1,frames);
  await expect(page.locator('#toast')).not.toHaveClass(/show/, {timeout:15000});
  const layout=await page.evaluate(()=>{
    const rect=s=>document.querySelector(s).getBoundingClientRect().toJSON();
    return {width:innerWidth, scrollWidth:document.documentElement.scrollWidth, scene:rect('#scene'), lesson:rect('.lesson-card'), console:rect('.simulation-console'), dock:rect('.control-dock')};
  });
  assert.ok(layout.scene.height>=220, `${name}: visible sailing scene`);
  assert.ok(layout.dock.height<=Math.max(height*.45,340), `${name}: bounded controls`);
  if(layout.lesson.height && width<650) {
    assert.ok(layout.lesson.top>=layout.scene.bottom-1, `${name}: lesson below the sailing view`);
    if(layout.console.height)assert.ok(layout.lesson.bottom<=layout.console.top+1, `${name}: lesson does not overlap playback`);
  }
  await expect(page.locator('#mobile-camera')).toBeVisible();
  await page.screenshot({path:`artifacts/mobile/${name}.png`,fullPage:true,timeout:120000});
  results.push({name,...layout});
  console.log(`${name}: no horizontal overflow, scene and controls fit.`);
}
try {
  await page.goto(process.argv.find(arg=>arg.startsWith('--url='))?.slice(6)||process.env.SAIL_URL||'http://127.0.0.1:5187', {waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('#scene')?.dataset.drawCalls, null, {timeout:120000});
  await expect(page.locator('.mobile-lesson')).toHaveCount(42);
  await expect(page.locator('.mobile-lesson[aria-current]')).toHaveAttribute('data-mobile-lesson','0');
  await expect(page.locator('.simulation-console')).toBeHidden();
  await inspect('phone-lessons',390,844);
  await page.locator('[data-mobile-lesson="8"]').click();
  await expect(page.locator('.mobile-lesson[aria-current]')).toHaveAttribute('data-mobile-lesson','8');
  await expect(page.locator('#card-title')).toContainText('beam reach');
  await expect(page.locator('body')).toHaveAttribute('data-activity','ready');
  await page.locator('.mobile-course-heading button').click();
  await expect(page.locator('.course-library')).toBeVisible();
  await page.locator('[data-library-lesson="2"]').click();
  await expect(page.locator('.mobile-lesson[aria-current]')).toHaveAttribute('data-mobile-lesson','2');
  await page.locator('[data-mode="explore"]').click();
  await expect(page.locator('.mobile-course')).toBeHidden();
  await expect(page.locator('.control-dock')).toBeHidden();
  await inspect('phone-folded',390,844);
  const sceneBefore=await page.locator('#scene').boundingBox();
  await page.locator('#mobile-controls-toggle').click();
  await expect(page.locator('#mobile-controls-toggle')).toHaveAttribute('aria-expanded','true');
  await page.keyboard.press('Tab');
  await expect(page.locator('#mobile-tab-helm')).toBeFocused();
  await expect(page.locator('#rudder')).toBeVisible();
  assert.deepEqual(await page.locator('#scene').boundingBox(),sceneBefore,'Opening controls must not shrink or move the scene');
  await inspect('phone-controls',390,844);
  await page.locator('#rudder').fill('12');
  await expect(page.locator('#rudder-value')).toContainText('12');
  await page.locator('#center-helm').click();
  await expect(page.locator('#rudder')).toHaveValue('0');
  await page.locator('#engine-throttle').fill('0.5');
  await page.locator('#engine-neutral').click();
  await expect(page.locator('#engine-throttle')).toHaveValue('0');
  await page.locator('#mobile-tab-sails').click();
  await expect(page.locator('#rudder')).toBeHidden();
  await page.locator('#cockpit-main-hoist').selectOption('0.5');
  await page.locator('#trim').fill('30');
  await page.locator('#cockpit-jib-sheet').fill('35');
  await page.locator('#mobile-tab-anchor').click();
  await page.locator('#cockpit-anchor-rode').fill('25');
  await page.locator('#mobile-tab-instruments').click();
  await expect(page.locator('#helm-dashboard')).toBeVisible();
  await page.locator('#dashboard-enlarge').click();
  await expect(page.locator('.dashboard-expanded')).toBeVisible();
  await page.locator('#dashboard-close').click();
  await page.locator('#mobile-tab-instruments').focus();
  await page.keyboard.press('Home');
  await expect(page.locator('#mobile-tab-helm')).toBeFocused();
  await expect(page.locator('#mobile-tab-helm')).toHaveAttribute('aria-selected','true');
  await page.keyboard.press('Escape');
  await expect(page.locator('.control-dock')).toBeHidden();
  await expect(page.locator('#mobile-controls-toggle')).toBeFocused();
  await page.locator('#mobile-camera').selectOption('deck');
  await expect(page.locator('.simulator')).toHaveAttribute('data-view','deck');
  await page.locator('#mobile-camera').selectOption('chase');
  await page.locator('#systems-toggle').click();
  await expect(page.locator('#systems-drawer')).toBeVisible();
  await page.locator('#vessel-mainHoist').fill('0.25');
  await page.locator('#systems-close').click();
  await page.locator('#help').click();
  await expect(page.locator('#modal')).toBeVisible();
  await page.locator('#close-modal').click();
  await page.locator('[data-mode="learn"]').click();
  await page.locator('[data-mobile-lesson="8"]').click();
  await page.locator('#lesson-briefing').click();
  await expect(page.locator('#lesson-reader')).toBeVisible();
  await page.locator('#reader-close').click();
  await page.locator('#practice-start').click();
  await page.locator('#practice-launch').click();
  await expect(page.locator('body')).toHaveAttribute('data-activity','training-running');
  await page.locator('#play').click();
  await expect(page.locator('body')).toHaveAttribute('data-activity','training-paused');
  await expect(page.locator('.mobile-practice-details')).not.toHaveAttribute('open','');
  await inspect('phone-practice',390,844);
  await page.locator('.mobile-practice-details summary').click();
  await expect(page.locator('#practice-requirements')).toBeVisible();
  await page.setViewportSize({width:1440,height:1000});
  await expect(page.locator('.sidebar')).toBeVisible();
  await expect(page.locator('#practice-end')).toBeVisible();
  for(const id of ['rudder','trim','cockpit-main-hoist','cockpit-anchor-rode','helm-dashboard'])await expect(page.locator(`#${id}`)).toBeVisible();
  await page.screenshot({path:'artifacts/mobile/desktop.png',fullPage:true,timeout:120000});
  await page.locator('#practice-end').click();
  await page.locator('#close-modal').click();
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-mobile-lesson="0"]').click();
  await inspect('small-phone',320,568);
  await inspect('landscape',844,390);
  await inspect('tablet',768,1024);
  await page.setViewportSize({width:390,height:844});
  await page.locator('.text-size-control > summary').click();
  await page.locator('#sail-text-size-range').fill('200');
  await page.locator('.text-size-control > summary').click();
  await inspect('large-text',390,844);
  await page.locator('#language-select').selectOption('he');
  await expect(page.locator('html')).toHaveAttribute('lang','he',{timeout:120000});
  await page.waitForFunction(()=>document.querySelector('#scene')?.dataset.drawCalls, null, {timeout:120000});
  await inspect('hebrew-large-text',390,844);
  await page.locator('[data-mode="explore"]').click();
  await page.locator('#mobile-controls-toggle').click();
  await page.locator('#mobile-tab-sails').click();
  await inspect('hebrew-controls-large-text',390,844);
  await page.locator('#cockpit-main-hoist').selectOption('1');
  assert.deepEqual(errors,[]);
  await writeFile('artifacts/mobile/check.json',JSON.stringify({passed:true,results,errors},null,2));
  console.log('Mobile checks passed: lesson selection, folding overlay, tabs, controls, live practice, desktop, phone, landscape, tablet, large text and RTL.');
} finally { await browser.close(); }
