import { LANGUAGES, getLanguage } from './i18n/runtime.js';
import { playbackIcon } from './activity/playback-icon.js';

const icons = {
  sail: '<path d="M12 3v16H3L12 3Zm3 4 6 12h-6V7ZM3 22h18"/>',
  compass: '<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6 6-2Z"/>',
  book: '<path d="M12 5v16M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2V4Z"/>',
  flag: '<path d="M5 22V3c5-4 9 4 14 0v10c-5 4-9-4-14 0"/>',
  chart: '<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',
  wind: '<path d="M3 8h13a3 3 0 1 0-3-3M3 12h16a3 3 0 1 1-3 3M3 16h6a3 3 0 1 1-3 3"/>',
  anchor:
    '<circle cx="12" cy="4" r="2"/><path d="M12 6v15M8 9h8M3 14v3l3-1m15-2v3l-3-1M3 17c4 6 14 6 18 0"/>',
  settings:
    '<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>',
  arrow: '<path d="m9 5 7 7-7 7"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',
  help: '<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3c-1 0-1 1-1 2m0 3v.1"/>',
  reset: '<path d="M3 10a9 9 0 1 1 1 8M3 4v6h6"/>',
  eye: '<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
  helm: '<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/><path d="M12 2v8m0 4v8M2 12h8m4 0h8M5 5l5 5m4 4 5 5M5 19l5-5m4-4 5-5"/>',
  cockpit:
    '<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8" cy="11" r="2"/><path d="M14 9h4m-4 4h4M6 16h12"/>',
};
const icon = (name, className = '') =>
  `<svg class="${className}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.sail}</svg>`;

export function mountAppShell({ lessonCount, mode }) {
  document.querySelector('#app').innerHTML = `
<header class="topbar"><a class="brand" href="${import.meta.env.BASE_URL}" aria-label="Sail home">${icon('sail')}<span>SAIL<span class="brand-dot">.</span></span></a><div class="brand-caption">A LITTLE CLOSER TO THE SEA</div><nav aria-label="Main navigation"><button class="nav-item active" data-mode="learn">Learn to sail</button><button class="nav-item" data-mode="explore">Free sailing</button><button class="nav-item" data-mode="challenge">Challenges</button></nav><div class="language-switch"><label for="language-select">Language</label><select id="language-select" aria-label="Language" title="Changing language restarts the current practice. Completed lessons and quiz results are preserved.">${LANGUAGES.map((l) => `<option value="${l.code}" lang="${l.code}" ${getLanguage() === l.code ? 'selected' : ''}>${l.name}</option>`).join('')}</select></div><div id="text-size-control"></div><button id="help" class="icon-button" aria-label="Help">${icon('help')}</button><span class="preview-badge">EARLY ACCESS <i></i></span></header>
<main class="workspace"><aside class="sidebar"><div class="sidebar-heading"><div class="eyebrow">THE SAILING SCHOOL</div><h1>Your sea legs<br>start here.</h1><p>A little curiosity. A little practice.<br>A whole new point of view.</p></div><div class="course-progress"><div><span>Your sailing curriculum</span><span id="progress-label" dir="ltr">0 / ${lessonCount}</span></div><div class="progress-track"><div id="progress-fill"></div></div></div><div id="lessons" class="lesson-list"></div><div class="sidebar-bottom"><span class="small-icon">${icon('compass')}</span><div><strong>Learn at your own pace</strong><p>There’s no rush on the water.</p></div></div><button id="reference" class="reference-link">Learning library <span>↗</span></button></aside>
<section class="simulator" data-mode="${mode}" aria-label="Sailing simulator"><div id="scene"></div><div class="scene-vignette"></div><div class="scene-tools"><div class="scene-conditions"><button id="location-select" class="location location-button" aria-label="Change location"><div class="live-dot"></div><div><strong id="location-title">Haven Islands</strong><span><span style="display:inline">Change location</span> ▾</span></div></button><div class="weather">${icon('sun')}<span>Clear skies</span><span class="weather-divider"></span>${icon('wind')}<strong id="weather-wind">12 kn NW</strong></div></div>
<div class="view-controls"><div class="camera-views" role="group" aria-label="Camera view"><button class="selected" data-camera="chase" aria-pressed="true" aria-label="Chase" title="Chase">${icon('eye')}<span class="session-camera-label">Chase</span></button><button data-camera="helm" aria-pressed="false" aria-label="Helm" title="Helm">${icon('helm', 'session-camera-icon')}<span class="session-camera-label">Helm</span></button><button data-camera="deck" aria-pressed="false" aria-label="Cockpit" title="Cockpit">${icon('cockpit', 'session-camera-icon')}<span class="session-camera-label">Cockpit</span></button></div><button id="chart-toggle" aria-label="Open navigation chart">${icon('chart')}<span>CHART</span></button><button id="systems-toggle" aria-expanded="false" aria-controls="systems-drawer">Systems</button></div>
</div>
<div id="lesson-cover" class="lesson-cover"><div class="scene-title"><span>LESSON <span id="lesson-number">01</span> / ${lessonCount}</span><h2 id="scene-heading">Meet your boat.</h2><p id="scene-subheading">Take the helm. Find your rhythm.</p></div></div>
<aside id="systems-drawer" class="systems-drawer" aria-label="Vessel systems" hidden><button id="systems-close" aria-label="Close vessel systems">×</button><div id="vessel-controls"></div></aside><div class="right-instruments"><div class="wind-card"><div class="instrument-label">Wind over water</div><div class="wind-dial"><span class="dial-n">N</span><span class="dial-e">E</span><span class="dial-s">S</span><span class="dial-w">W</span><div class="no-go"></div><svg id="wind-arrow" viewBox="0 0 100 100"><path d="M50 14v60M43 25l7-12 7 12" fill="none" stroke="#e9b87c" stroke-width="2"/></svg><svg class="dial-boat" viewBox="0 0 40 60"><path d="M20 3C8 17 8 42 11 53h18c3-11 3-36-9-50Z" fill="#edf5ed"/><path d="M20 12v33" stroke="#31505a"/></svg></div><div class="wind-value"><strong id="wind-value">12.0</strong><span>knots</span></div><div id="point-of-sail" class="point-of-sail">Beam reach</div></div><button id="chart-preview" class="chart-card" aria-label="Open navigation chart"><div><span>CHART</span>${icon('chart')}</div><canvas id="mini-chart" width="240" height="170"></canvas><span class="chart-footer"><span id="chart-location-title">Haven Islands</span><span>↗</span></span></button></div>
<div class="lesson-card"><div class="lesson-card-icon">${icon('compass')}</div><div class="lesson-copy"><div class="eyebrow" id="card-eyebrow">LET’S GET UNDERWAY</div><h3 id="card-title">Make yourself at home.</h3><div id="lesson-training-type" class="lesson-training-type" hidden></div><p id="card-body"></p><div class="objective"><span id="objective-check">○</span><span id="objective-text"></span></div></div><button id="next-lesson" class="next-button" aria-label="Next lesson">${icon('arrow')}</button></div>
<div class="scene-footer"><span><i></i> <span id="sim-status">Ready when you are</span></span><span>Drag to look around <b>·</b> Scroll to zoom</span></div>
<div class="control-dock"><div class="speed-display"><span class="instrument-label">BOAT SPEED</span><div><strong id="speed">0.0</strong><span>kn</span></div><span id="speed-caption">Ready to get underway</span></div><div class="heading-display"><span class="instrument-label">HEADING</span><div><strong id="heading">035</strong><span>°</span></div><span id="heading-caption">NE</span></div><div class="helm-control"><div class="control-title"><label for="rudder">HELM</label><span id="rudder-value">Centered</span></div><div class="helm-range"><span>P</span><input id="rudder" type="range" min="-35" max="35" value="0" aria-label="Helm angle"><span>S</span></div><div class="control-hint"><kbd>←</kbd><kbd>→</kbd><span>steer</span><button id="center-helm">Center</button></div></div><div class="sail-control"><div class="control-title"><label for="trim">MAINSHEET</label><span id="trim-value">45%</span></div><input id="trim" type="range" min="0" max="90" value="45" aria-label="Mainsheet trim"><div class="control-hint"><span>In</span><span id="ideal-trim">Suggested: 28%</span><span>Out</span></div></div><div class="engine-control"><div class="control-title"><label for="engine-throttle">Engine control</label><span id="engine-throttle-value">Neutral</span></div><input id="engine-throttle" type="range" min="-1" max="1" step="0.05" value="0" aria-label="Engine throttle"><div class="control-hint"><span>Astern</span><button id="engine-neutral" class="engine-neutral">Neutral</button><span>Ahead</span></div></div><div class="sail-actions"><button id="sails">${icon('sail')}<span>Lower sails</span></button><button id="reef">${icon('wind')}<span>Reef</span></button></div><div class="play-actions"><button id="play" class="primary-button">${playbackIcon()} <span>Set sail</span></button><button id="conditions" title="Conditions">${icon('settings')}<span>Conditions</span></button><button id="reset" aria-label="Reset boat" title="Reset boat">${icon('reset')}</button><button id="anchor">${icon('anchor')}<span>Drop anchor</span></button></div></div>
</section></main><dialog id="modal"><div id="modal-content"></div><button id="close-modal" class="modal-close" aria-label="Close dialog">×</button></dialog><div id="toast" role="status"></div>`;
}
