import './style.css';
import { createScene } from './scene.js';
import { initialState, step, angleDifference, pointOfSail, clamp, islands, buoys } from './physics.js';

const icons={sail:'<path d="M12 3v16H3L12 3Zm3 4 6 12h-6V7ZM3 22h18"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6 6-2Z"/>',book:'<path d="M12 5v16M3 4c4-1 6 0 9 2 3-2 5-3 9-2v15c-4-1-6 0-9 2-3-2-5-3-9-2V4Z"/>',flag:'<path d="M5 22V3c5-4 9 4 14 0v10c-5 4-9-4-14 0"/>',chart:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',wind:'<path d="M3 8h13a3 3 0 1 0-3-3M3 12h16a3 3 0 1 1-3 3M3 16h6a3 3 0 1 1-3 3"/>',anchor:'<circle cx="12" cy="4" r="2"/><path d="M12 6v15M8 9h8M3 14v3l3-1m15-2v3l-3-1M3 17c4 6 14 6 18 0"/>',settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>',arrow:'<path d="m9 5 7 7-7 7"/>',check:'<path d="m5 12 4 4L19 6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3c-1 0-1 1-1 2m0 3v.1"/>',reset:'<path d="M3 10a9 9 0 1 1 1 8M3 4v6h6"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>'};
const icon=(name)=>`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.sail}</svg>`;
const lessons=[
 {title:'Meet your boat',sub:'Your first moment at the helm',body:'Welcome aboard. This is your space to learn by doing. Get underway, then hold a steady course while your boat gathers speed.',goal:'Reach 3 knots under sail',tip:'Your sails are already raised. Select Set sail to begin.',test:s=>s.speed>=3},
 {title:'Find the wind',sub:'Understand your point of sail',body:'You cannot sail directly into the wind. Turn the helm to find a beam reach, with the wind coming across the side of your boat.',goal:'Hold a beam reach for 5 seconds',tip:'Aim for a true wind angle between 80° and 105°. Center the helm to stop turning.',test:s=>Math.abs(angleDifference(s.heading,s.windDirection))>=80&&Math.abs(angleDifference(s.heading,s.windDirection))<=105,duration:5},
 {title:'Trim your sails',sub:'A little adjustment, a little more speed',body:'Ease the mainsheet as you turn away from the wind; pull it in as you head closer. Find the trim that lets your boat sail freely.',goal:'Match the recommended trim for 5 seconds',tip:'Use the mainsheet slider. The suggested setting changes with your course.',test:s=>Math.abs(s.trim-clamp((Math.abs(angleDifference(s.heading,s.windDirection))-35)/1.6,5,88))<6&&s.speed>2,duration:5},
 {title:'Make a tack',sub:'Bring the bow through the wind',body:'A tack changes which side of the boat the wind comes from. Steer through the wind, then center the helm and regain speed on the other side.',goal:'Change tack and regain 2 knots',tip:'Watch the wind instrument. Keep turning through the no-go zone.',test:(s,ctx)=>Math.sign(angleDifference(s.heading,s.windDirection))!==ctx.tack&&s.speed>2&&Math.abs(angleDifference(s.heading,s.windDirection))>40},
 {title:'Reef the mainsail',sub:'Less sail, more control',body:'Reefing reduces sail area when the breeze builds. Use the reef control and feel how the yacht settles with less power in the sail.',goal:'Sail with one reef for 5 seconds',tip:'Select Reef below the mainsheet control.',test:s=>s.reef&&s.speed>1,duration:5},
 {title:'Come to rest',sub:'Finish your first passage',body:'Lower your sails, allow your boat to slow, and drop the anchor. This prototype models anchoring as a simple brake.',goal:'Lower sails and stop at anchor',tip:'Select Lower sails, then Drop anchor.',test:s=>s.anchor&&!s.sails&&s.speed<.3}
];
let saved=[];try{saved=JSON.parse(localStorage.getItem('sail-lessons')||'[]');if(!Array.isArray(saved))saved=[];}catch{}
let completed=new Set(saved), lesson=0, lessonTime=0, lessonContext={tack:1}, state=initialState(), paused=true, mode='learn', camera='chase', challengeIndex=0, challengeDone=false, challengeTime=0;
document.querySelector('#app').innerHTML=`
<header class="topbar"><a class="brand" href="/" aria-label="Sail home">${icon('sail')}<span>SAIL<span class="brand-dot">.</span></span></a><div class="brand-caption">A LITTLE CLOSER TO THE SEA</div><nav aria-label="Main navigation"><button class="nav-item active" data-mode="learn">Learn to sail</button><button class="nav-item" data-mode="explore">Free sailing</button><button class="nav-item" data-mode="challenge">Challenges</button></nav><button id="help" class="icon-button" aria-label="Help and keyboard controls">${icon('help')}</button><span class="preview-badge">EARLY ACCESS <i></i></span></header>
<main class="workspace"><aside class="sidebar"><div class="sidebar-heading"><div class="eyebrow">THE SAILING SCHOOL</div><h1>Your sea legs<br>start here.</h1><p>A little curiosity. A little practice.<br>A whole new point of view.</p></div><div class="course-progress"><div><span>Your first passage</span><span id="progress-label">0 / 6</span></div><div class="progress-track"><div id="progress-fill"></div></div></div><div id="lessons" class="lesson-list"></div><div class="sidebar-bottom"><span class="small-icon">${icon('compass')}</span><div><strong>Learn at your own pace</strong><p>There’s no rush on the water.</p></div></div><button id="reference" class="reference-link">Inspired by the world of sailing <span>↗</span></button></aside>
<section class="simulator" aria-label="Sailing simulator"><div id="scene"></div><div class="scene-vignette"></div><div class="location"><div class="live-dot"></div><div><strong>Haven Islands</strong><span>THE PRACTICE GROUNDS</span></div></div><div class="weather">${icon('sun')}<span>Clear skies</span><span class="weather-divider"></span>${icon('wind')}<strong id="weather-wind">12 kn NW</strong></div>
<div class="scene-title"><span>LESSON <span id="lesson-number">01</span> / 06</span><h2 id="scene-heading">Meet your boat.</h2><p id="scene-subheading">Take the helm. Find your rhythm.</p></div>
<div class="view-controls" role="group" aria-label="Camera view"><button class="selected" data-camera="chase">${icon('eye')}<span>Chase</span></button><button data-camera="helm">Helm</button><button data-camera="deck">Cockpit</button><button data-camera="aerial">Aerial</button></div>
<div class="right-instruments"><div class="wind-card"><div class="instrument-label">TRUE WIND</div><div class="wind-dial"><span class="dial-n">N</span><span class="dial-e">E</span><span class="dial-s">S</span><span class="dial-w">W</span><div class="no-go"></div><svg id="wind-arrow" viewBox="0 0 100 100"><path d="M50 14v60M43 25l7-12 7 12" fill="none" stroke="#e9b87c" stroke-width="2"/></svg><svg class="dial-boat" viewBox="0 0 40 60"><path d="M20 3C8 17 8 42 11 53h18c3-11 3-36-9-50Z" fill="#edf5ed"/><path d="M20 12v33" stroke="#31505a"/></svg></div><div class="wind-value"><strong id="wind-value">12.0</strong><span>knots</span></div><div id="point-of-sail" class="point-of-sail">Beam reach</div></div><button id="chart-toggle" class="chart-card" aria-label="Open navigation chart"><div><span>CHART</span>${icon('chart')}</div><canvas id="mini-chart" width="240" height="170"></canvas><span class="chart-footer">Haven Islands <span>↗</span></span></button></div>
<div class="lesson-card"><div class="lesson-card-icon">${icon('compass')}</div><div class="lesson-copy"><div class="eyebrow" id="card-eyebrow">LET’S GET UNDERWAY</div><h3 id="card-title">Make yourself at home.</h3><p id="card-body"></p><div class="objective"><span id="objective-check">○</span><span id="objective-text"></span></div></div><button id="next-lesson" class="next-button" aria-label="Next lesson">${icon('arrow')}</button></div>
<div class="scene-footer"><span><i></i> <span id="sim-status">Ready when you are</span></span><span>Drag to look around <b>·</b> Scroll to zoom</span></div>
<div class="control-dock"><div class="speed-display"><span class="instrument-label">BOAT SPEED</span><div><strong id="speed">0.0</strong><span>kn</span></div><span id="speed-caption">Ready to get underway</span></div><div class="heading-display"><span class="instrument-label">HEADING</span><div><strong id="heading">035</strong><span>°</span></div><span id="heading-caption">NE</span></div><div class="helm-control"><div class="control-title"><label for="rudder">HELM</label><span id="rudder-value">Centered</span></div><div class="helm-range"><span>P</span><input id="rudder" type="range" min="-35" max="35" value="0" aria-label="Helm angle"><span>S</span></div><div class="control-hint"><kbd>←</kbd><kbd>→</kbd><span>steer</span><button id="center-helm">Center</button></div></div><div class="sail-control"><div class="control-title"><label for="trim">MAINSHEET</label><span id="trim-value">45%</span></div><input id="trim" type="range" min="0" max="90" value="45" aria-label="Mainsheet trim"><div class="control-hint"><span>In</span><span id="ideal-trim">Suggested: 28%</span><span>Out</span></div></div><div class="sail-actions"><button id="sails">${icon('sail')}<span>Lower sails</span></button><button id="reef">${icon('wind')}<span>Reef</span></button></div><div class="play-actions"><button id="play" class="primary-button">▶ <span>Set sail</span></button><button id="anchor">${icon('anchor')}<span>Drop anchor</span></button></div></div>
</section></main><footer class="bottom-bar"><span>${icon('sail')} A world of possibility. One nautical mile at a time.</span><div><span id="depth">DEPTH <b>28.0 m</b></span><button id="conditions">${icon('settings')} Conditions</button><button id="reset" aria-label="Reset boat">${icon('reset')}</button></div></footer><dialog id="modal"><div id="modal-content"></div><button id="close-modal" class="modal-close" aria-label="Close dialog">×</button></dialog><div id="toast" role="status"></div>`;
const $=s=>document.querySelector(s);
let scene;
try{scene=createScene($('#scene'));}catch(error){$('#scene').innerHTML='<div class="webgl-fallback"><h2>A browser with WebGL is needed for the 3D view.</h2><p>You can still use the chart, controls, and lessons.</p></div>';console.error(error);}

function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function renderLessons(){
 $('#lessons').innerHTML=lessons.map((l,i)=>`<button class="lesson-row ${lesson===i&&mode==='learn'?'current':''} ${completed.has(i)?'complete':''}" data-lesson="${i}"><span class="lesson-index">${completed.has(i)?icon('check'):String(i+1).padStart(2,'0')}</span><span><strong>${l.title}</strong><small>${i<2?'THE FOUNDATIONS':i<4?'WORKING WITH THE WIND':'FINDING YOUR CONFIDENCE'}</small></span>${icon('arrow')}</button>`).join('');
 $('#progress-label').textContent=`${completed.size} / 6`;$('#progress-fill').style.width=`${completed.size/6*100}%`;
 document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{lesson=Number(b.dataset.lesson);setMode('learn');});
}
function updateLesson(){lessonTime=0;lessonContext={tack:Math.sign(angleDifference(state.heading,state.windDirection))||1};const l=lessons[lesson];
 $('#lesson-number').textContent=String(lesson+1).padStart(2,'0');$('#scene-heading').textContent=l.title+'.';$('#scene-subheading').textContent=l.sub;
 $('#card-eyebrow').textContent=`YOUR FIRST PASSAGE · ${String(lesson+1).padStart(2,'0')}`;$('#card-title').textContent=l.goal;$('#card-body').textContent=l.body;$('#objective-text').textContent=l.tip;
 $('#objective-check').textContent=completed.has(lesson)?'✓':'○';$('#next-lesson').hidden=lesson===lessons.length-1;renderLessons();}
function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('.scene-title>span').style.visibility=mode==='learn'?'visible':'hidden';
 if(mode==='learn')updateLesson();else{
   renderLessons();$('#scene-heading').textContent=mode==='explore'?'Follow your curiosity.':'Find your next mark.';$('#scene-subheading').textContent=mode==='explore'?'No route. No rush. Just the sea.':'Three buoys. One beautiful passage.';
   $('#card-eyebrow').textContent=mode==='explore'?'FREE SAILING':'THE BUOY COURSE';$('#card-title').textContent=mode==='explore'?'The islands are yours.':'Round the three amber buoys.';
   $('#card-body').textContent=mode==='explore'?'Explore the coastline, experiment with sail trim, or change the breeze in Conditions. Open your chart to plan a passage.':'Sail within 35 metres of each buoy in order. Use your chart to locate the next mark and keep clear of shallow water.';
   $('#objective-text').textContent=mode==='explore'?'Try the helm camera for a view from aboard.':`Next mark: buoy ${challengeIndex+1} of 3`;
   $('#objective-check').textContent='○';$('#next-lesson').hidden=true;
 }
}
function syncControls(){ $('#rudder').value=state.rudder;$('#trim').value=state.trim;$('#rudder-value').textContent=Math.abs(state.rudder)<.5?'Centered':`${Math.abs(state.rudder).toFixed(0)}° ${state.rudder<0?'port':'starboard'}`;$('#trim-value').textContent=`${state.trim.toFixed(0)}%`;$('#sails span').textContent=state.sails?'Lower sails':'Raise sails';$('#reef').classList.toggle('on',state.reef);$('#reef span').textContent=state.reef?'Reefed':'Reef';$('#anchor span').textContent=state.anchor?'Weigh anchor':'Drop anchor';$('#anchor').classList.toggle('on',state.anchor);$('#play').innerHTML=paused?'▶ <span>Set sail</span>':'Ⅱ <span>Pause</span>';}
$('#rudder').oninput=e=>{state.rudder=Number(e.target.value);syncControls();};$('#trim').oninput=e=>{state.trim=Number(e.target.value);syncControls();};
$('#center-helm').onclick=()=>{state.rudder=0;syncControls();};$('#play').onclick=()=>{paused=!paused;syncControls();};
$('#sails').onclick=()=>{state.sails=1-state.sails;syncControls();toast(state.sails?'Sails raised. Find the wind.':'Sails lowered. Your boat will coast to a stop.');};
$('#reef').onclick=()=>{state.reef=!state.reef;syncControls();};$('#anchor').onclick=()=>{state.anchor=!state.anchor;syncControls();toast(state.anchor?'Anchor down.':'Anchor weighed. You’re free to sail.');};
$('#next-lesson').onclick=()=>{lesson=Math.min(lesson+1,5);updateLesson();};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{camera=b.dataset.camera;scene?.setView(camera);$('.simulator').dataset.view=camera;document.querySelectorAll('[data-camera]').forEach(btn=>btn.classList.toggle('selected',btn===b));});
$('#reset').onclick=()=>{state=initialState();paused=true;challengeIndex=0;challengeDone=false;challengeTime=0;setMode(mode);syncControls();toast('Boat returned to the practice grounds. Your lesson progress is saved.');};
function openModal(content){$('#modal-content').innerHTML=content;$('#modal').showModal();}
$('#close-modal').onclick=()=>$('#modal').close();$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close();});
$('#help').onclick=()=>openModal(`<div class="eyebrow">WELCOME ABOARD</div><h2>A few things before you sail.</h2><p>Use the helm to steer and the mainsheet to adjust your sail. Select Cockpit to inspect the winches, ropes, and live instruments, or Helm to sail from behind the wheel. The wind comes from the direction shown on the instrument. Your yacht loses power when pointed within 38° of the wind.</p><div class="help-grid"><span><kbd>←</kbd> <kbd>→</kbd> Steer port / starboard</span><span><kbd>↑</kbd> <kbd>↓</kbd> Trim in / ease out</span><span><kbd>Space</kbd> Pause / sail</span><span><kbd>C</kbd> Center the helm</span><span><kbd>M</kbd> Open chart</span><span>Drag to look around · Scroll to zoom</span></div><p>Lessons save automatically in this browser. Explore freely or follow the six introductory exercises.</p><div class="modal-note">An experimental learning playground with simplified physics. It is not a substitute for on-water instruction.</div>`);
$('#conditions').onclick=()=>{openModal(`<div class="eyebrow">MAKE IT YOUR OWN</div><h2>A change in the weather.</h2><p>A steady breeze is a good place to start.</p><label class="setting-label" for="wind-speed">Wind speed <strong id="wind-speed-value">${state.windSpeed} kn</strong></label><input id="wind-speed" type="range" min="3" max="30" value="${state.windSpeed}"><label class="setting-label" for="wind-direction">Wind from <strong id="wind-direction-value">${state.windDirection}°</strong></label><input id="wind-direction" type="range" min="0" max="359" value="${state.windDirection}"><p class="modal-note">Wind changes take effect immediately. Try reefing the mainsail as the breeze picks up.</p>`);$('#wind-speed').oninput=e=>{state.windSpeed=+e.target.value;$('#wind-speed-value').textContent=state.windSpeed+' kn';};$('#wind-direction').oninput=e=>{state.windDirection=+e.target.value;$('#wind-direction-value').textContent=state.windDirection+'°';};};
$('#reference').onclick=async()=>{let summary;try{summary=await fetch('/reference-summary.json').then(r=>r.json());}catch{}
 openModal(`<div class="eyebrow">THE REFERENCE LIBRARY</div><h2>Inspired by real seamanship.</h2><p>This original browser prototype draws on the learning themes of <a href="https://www.esailyachtsimulator.com/the-world-of-esail/learn-to-sail/" target="_blank" rel="noreferrer">eSail’s Learn to Sail</a>: boat handling, sail trim, tacking, reefing, and anchoring.</p><div class="archive-stats"><div><strong>${summary?.pages??'—'}</strong><span>pages archived</span></div><div><strong>${summary?.images??'—'}</strong><span>images collected</span></div></div><p>The local reference archive includes original HTML, extracted text, images, and a source manifest in <code>reference/esail/</code>. The simulator uses original geometry and lesson text.</p><div class="modal-note">Independent prototype. Not affiliated with eSail. Source assets remain attributed to their respective owners.</div>`);
};
function drawChart(canvas){if(!canvas)return;const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#173d47';ctx.fillRect(0,0,w,h);const scale=w/2200, map=(x,z)=>[w*.5+x*scale,h*.5+(z+100)*scale];
 ctx.strokeStyle='#ffffff0b';ctx.lineWidth=1;for(let x=0;x<w;x+=w/8){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=w/8){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
 for(const i of islands){const [x,y]=map(i.x,i.z);ctx.fillStyle='#577669';ctx.strokeStyle='#8eaa8a';ctx.beginPath();ctx.ellipse(x,y,i.rx*scale,i.rz*scale,.2,0,Math.PI*2);ctx.fill();ctx.stroke();if(w>300){ctx.fillStyle='#c5d4c2';ctx.font='13px sans-serif';ctx.textAlign='center';ctx.fillText(i.name,x,y+5);}}
 buoys.forEach((b,i)=>{const [x,y]=map(b.x,b.z);ctx.fillStyle=i===challengeIndex?'#f4c87b':'#b48d4f';ctx.beginPath();ctx.arc(x,y,w>300?6:3,0,Math.PI*2);ctx.fill();if(w>300){ctx.fillText(String(i+1),x+14,y+5);}});
 const [x,y]=map(state.x,state.z);ctx.save();ctx.translate(x,y);ctx.rotate(state.heading*Math.PI/180);ctx.fillStyle='#f4f2da';ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(5,6);ctx.lineTo(0,3);ctx.lineTo(-5,6);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#a7c4c5';ctx.font=`${w>300?13:10}px sans-serif`;ctx.textAlign='left';ctx.fillText('N ↑',12,21);ctx.fillText(w>300?'0 ━━━ 250 m':'250 m',12,h-12);
}
function openChart(){openModal(`<div class="eyebrow">NAVIGATION</div><h2>The Haven Islands.</h2><p>Your position updates live. Amber marks indicate the buoy course.</p><canvas id="large-chart" width="760" height="570"></canvas><div class="chart-legend"><span>▲ Your yacht</span><span>● Course buoys</span><span>Fictional practice waters</span></div>`);drawChart($('#large-chart'));}
$('#chart-toggle').onclick=openChart;
const keys=new Set();window.addEventListener('keydown',e=>{if($('#modal').open||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||(e.target.tagName==='BUTTON'&&e.key===' '))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();keys.add(e.key);if(e.repeat)return;if(e.key===' '){paused=!paused;syncControls();}if(e.key.toLowerCase()==='c'){state.rudder=0;syncControls();}if(e.key.toLowerCase()==='m')openChart();});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());
const compass=h=>['N','NE','E','SE','S','SW','W','NW'][Math.round(h/45)%8];
let last=performance.now(), uiTick=0, wasGrounded=false;
function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;
 if(!$('#modal').open){if(keys.has('ArrowLeft'))state.rudder=clamp(state.rudder-dt*25,-35,35);if(keys.has('ArrowRight'))state.rudder=clamp(state.rudder+dt*25,-35,35);if(keys.has('ArrowUp'))state.trim=clamp(state.trim-dt*22,0,90);if(keys.has('ArrowDown'))state.trim=clamp(state.trim+dt*22,0,90);if(keys.size)syncControls();}
 if(!paused){step(state,dt);
  if(mode==='learn'&&!completed.has(lesson)){if(lessons[lesson].test(state,lessonContext))lessonTime+=dt;else lessonTime=0;if(lessonTime>=(lessons[lesson].duration||.2)){completed.add(lesson);try{localStorage.setItem('sail-lessons',JSON.stringify([...completed]));}catch{}renderLessons();$('#objective-check').textContent='✓';toast(lesson===5?'First passage complete. The sea is yours!':'Lesson complete. Nicely sailed. Select the arrow for your next lesson.');}}
  if(mode==='challenge'&&!challengeDone){challengeTime+=dt;const target=buoys[challengeIndex];if(Math.hypot(state.x-target.x,state.z-target.z)<35){challengeIndex++;if(challengeIndex===buoys.length){challengeDone=true;$('#objective-text').textContent=`Course complete in ${Math.floor(challengeTime/60)}m ${Math.floor(challengeTime%60)}s`;toast('Three marks rounded. Course complete!');}else{$('#objective-text').textContent=`Next mark: buoy ${challengeIndex+1} of 3`;toast(`Buoy ${challengeIndex} reached. On to the next mark.`);}}}
 }
 if(state.grounded&&!wasGrounded)toast('You’ve reached shallow water. Use Reset boat to return to the practice grounds.');wasGrounded=state.grounded;
 scene?.render(state,now/1000);uiTick+=dt;
 if(uiTick>.12){uiTick=0;const twa=angleDifference(state.windDirection,state.heading);$('#speed').textContent=state.speed.toFixed(1);$('#heading').textContent=String(Math.round(state.heading)%360).padStart(3,'0');$('#heading-caption').textContent=compass(state.heading);$('#speed-caption').textContent=state.anchor?'At anchor':state.speed<.5?'Waiting for the breeze':pointOfSail(twa);$('#point-of-sail').textContent=pointOfSail(twa);$('#wind-arrow').style.transform=`rotate(${state.windDirection}deg)`;$('.dial-boat').style.transform=`rotate(${state.heading}deg)`;$('.no-go').style.transform=`rotate(${state.windDirection}deg)`;$('#wind-value').textContent=state.windSpeed.toFixed(1);$('#weather-wind').textContent=`${state.windSpeed} kn ${compass(state.windDirection)}`;$('#ideal-trim').textContent=`Suggested: ${Math.round(clamp((Math.abs(twa)-35)/1.6,5,88))}%`;$('#depth b').textContent=state.depth.toFixed(1)+' m';$('#sim-status').textContent=state.grounded?'Aground · Reset to recover':paused?'Ready when you are':state.anchor?'At anchor':'Underway · Your first adventure';drawChart($('#mini-chart'));if($('#modal').open)drawChart($('#large-chart'));}
 requestAnimationFrame(frame);
}
updateLesson();syncControls();requestAnimationFrame(frame);
