// One source for the visible operating state. Reading never masquerades as sailing.
export function activityState({reading=false,decisionOpen=false,decisionActive=false,practiceActive=false,practicePrepared=false,briefingOpen=false,practiceStatus='',paused=true,mode='learn',maneuverActive=false}={}){
 if(reading)return {id:'study',label:'STUDY MATERIAL',message:'Reading only. No simulation is running.',action:decisionActive||practiceActive?'Resume training':'Start simulation',command:'start',tone:'study'};
 if(decisionOpen)return decisionActive?{id:'scenario-running',label:'SCENARIO IN PROGRESS',message:'Your actions are being assessed. Complete the visible tasks.',tone:'running'}:{id:'review',label:'TRAINING REVIEW',message:'This attempt has ended. Review the score and recorded actions.',tone:'review'};
 if(practiceActive||maneuverActive)return paused||briefingOpen?{id:'training-paused',label:'SIMULATION PAUSED',message:'Your training attempt is preserved. Resume when ready.',action:'Resume simulation',command:'resume',tone:'paused'}:{id:'training-running',label:'SIMULATION RUNNING',message:'Live boat handling. Your actions are being assessed.',action:'Pause simulation',command:'pause',tone:'running'};
 if(practicePrepared)return {id:'briefing',label:'Simulation ready',message:'Exercise loaded. The boat is paused; scoring starts when you press Start simulation.',action:'Show briefing',command:'start',tone:'ready'};
 if(!paused)return {id:'free-running',label:'SIMULATION RUNNING',message:'Free practice. No assessed training attempt is active.',action:'Pause simulation',command:'pause',tone:'running'};
 if(mode==='learn'&&['passed','invalid'].includes(practiceStatus))return {id:'review',label:'TRAINING FINISHED',message:'Boat motion is paused. Review your result or start another attempt.',action:'Restart training',command:'start',tone:'review'};
 if(mode==='learn')return {id:'ready',label:'SIMULATION NOT STARTED',message:'The boat is stationary. Start simulation to begin an assessed task.',action:'Prepare simulation',command:'start',tone:'ready'};
 return {id:'free-paused',label:'SIMULATION PAUSED',message:'Boat motion is paused. Resume to sail freely.',action:'Resume simulation',command:'resume',tone:'paused'};
}
